import type { Locale } from "@/lib/i18n";

/**
 * Strings introduced by the Phase 2 flight-form rebuild. Kept local (same
 * pattern as the dashboard's LOCAL map) so lib/i18n.ts doesn't churn while
 * the form settles; fold them in later. Field labels, section titles and
 * common.save/cancel/delete still come from lib/i18n via makeT().
 *
 * Safe to import from both Server and Client Components (no server imports).
 */
const en = {
  newFlight: "New flight",
  editFlight: "Edit flight",
  newFlightDesc: "Log a flight. Only date, aircraft and time are required.",
  editFlightDesc: "Changes apply to your totals and currency as soon as you save.",
  backToFlights: "Back to flights",
  sectionCrew: "Crew",
  timeMeta: "Tenths of an hour",
  summaryTitle: "Summary",
  totalTime: "Total time",
  statInstrument: "Instrument",
  yes: "Yes",
  no: "No",
  readyToSave: "Ready to save",
  needsAttentionOne: "1 field needs attention",
  needsAttention: "{n} fields need attention",
  saveFlight: "Save flight",
  saveChanges: "Save changes",
  deleteFlight: "Delete flight",
  deleteQuestion: "Delete this flight?",
  deleteHelp: "It is removed from your totals and currency. This can't be undone.",
  confirmDelete: "Confirm delete",
  keep: "Keep",
  deleting: "Deleting…",
  discardQuestion: "Discard unsaved changes?",
  discardHelp: "Your edits to this flight won't be saved.",
  discard: "Discard",
  discarding: "Discarding…",
  keepEditing: "Keep editing",
  xcShort: "XC",
  errRequired: "Required",
  errEnterSomeTime: "Enter at least some time",
  errInvalidNumber: "Enter a number, e.g. 1.5",
  errMaxHours: "Max 24 h",
  errWholeNumber: "Whole numbers only",
  errMaxCount: "Max 999",
  errFutureDate: "Date can't be in the future",
  errInvalidDate: "Enter a valid date",
  errUnexpected: "Something went wrong while saving. Please try again.",
  warnInstrument: "Actual + hood exceeds day + night",
  regLookingUp: "Looking up {reg}…",
  regFound: "{reg} → {model}",
  regFromLogbook: "from your logbook",
  regFromRegistry: "TC/FAA registry",
  regUse: "Use ‘{reg} → {model}’",
  hintRoute: "ICAO codes, e.g. CYVR-CYYZ",
  hintApproaches: "Total — usually precision + non-precision",
  hintRemarks: "Ctrl/⌘ + Enter to save",
  takeoffsDay: "Takeoffs · day",
  takeoffsNight: "Takeoffs · night",
  landingsDay: "Landings · day",
  landingsNight: "Landings · night",
} as const;

export type FormStringKey = keyof typeof en;
type Table = Record<FormStringKey, string>;

const ko: Table = {
  newFlight: "새 비행",
  editFlight: "비행 편집",
  newFlightDesc: "비행을 기록하세요. 날짜, 기종, 시간만 필수입니다.",
  editFlightDesc: "저장하는 즉시 총계와 최신 유지 현황에 반영됩니다.",
  backToFlights: "비행 목록으로",
  sectionCrew: "승무원",
  timeMeta: "0.1시간 단위",
  summaryTitle: "요약",
  totalTime: "총 시간",
  statInstrument: "계기",
  yes: "예",
  no: "아니요",
  readyToSave: "저장 준비 완료",
  needsAttentionOne: "1개 항목을 확인하세요",
  needsAttention: "{n}개 항목을 확인하세요",
  saveFlight: "비행 저장",
  saveChanges: "변경사항 저장",
  deleteFlight: "비행 삭제",
  deleteQuestion: "이 비행을 삭제할까요?",
  deleteHelp: "총계와 최신 유지 현황에서 제거되며 되돌릴 수 없습니다.",
  confirmDelete: "삭제 확인",
  keep: "유지",
  deleting: "삭제 중…",
  discardQuestion: "저장하지 않은 변경사항을 버릴까요?",
  discardHelp: "이 비행에 대한 수정 내용이 저장되지 않습니다.",
  discard: "버리기",
  discarding: "버리는 중…",
  keepEditing: "계속 편집",
  xcShort: "장거리",
  errRequired: "필수 항목",
  errEnterSomeTime: "시간을 입력하세요",
  errInvalidNumber: "숫자를 입력하세요 (예: 1.5)",
  errMaxHours: "최대 24시간",
  errWholeNumber: "정수만 입력하세요",
  errMaxCount: "최대 999",
  errFutureDate: "미래 날짜는 입력할 수 없습니다",
  errInvalidDate: "올바른 날짜를 입력하세요",
  errUnexpected: "저장 중 문제가 발생했습니다. 다시 시도해 주세요.",
  warnInstrument: "실제 + 후드 시간이 주간 + 야간 시간을 초과합니다",
  regLookingUp: "{reg} 조회 중…",
  regFound: "{reg} → {model}",
  regFromLogbook: "내 로그북 기준",
  regFromRegistry: "TC/FAA 등록부",
  regUse: "‘{reg} → {model}’ 사용",
  hintRoute: "ICAO 코드, 예: CYVR-CYYZ",
  hintApproaches: "합계 — 보통 정밀 + 비정밀",
  hintRemarks: "Ctrl/⌘ + Enter로 저장",
  takeoffsDay: "이륙 · 주간",
  takeoffsNight: "이륙 · 야간",
  landingsDay: "착륙 · 주간",
  landingsNight: "착륙 · 야간",
};

const zh: Table = {
  newFlight: "新飞行",
  editFlight: "编辑飞行",
  newFlightDesc: "记录一次飞行。仅日期、机型和时间为必填。",
  editFlightDesc: "保存后立即更新您的总计和时效状态。",
  backToFlights: "返回飞行列表",
  sectionCrew: "机组",
  timeMeta: "以 0.1 小时为单位",
  summaryTitle: "摘要",
  totalTime: "总时间",
  statInstrument: "仪表",
  yes: "是",
  no: "否",
  readyToSave: "可以保存",
  needsAttentionOne: "1 个字段需要注意",
  needsAttention: "{n} 个字段需要注意",
  saveFlight: "保存飞行",
  saveChanges: "保存更改",
  deleteFlight: "删除飞行",
  deleteQuestion: "删除此次飞行？",
  deleteHelp: "将从您的总计和时效状态中移除，且无法撤销。",
  confirmDelete: "确认删除",
  keep: "保留",
  deleting: "正在删除…",
  discardQuestion: "放弃未保存的更改？",
  discardHelp: "您对此次飞行的修改将不会保存。",
  discard: "放弃",
  discarding: "正在放弃…",
  keepEditing: "继续编辑",
  xcShort: "越野",
  errRequired: "必填",
  errEnterSomeTime: "请输入时间",
  errInvalidNumber: "请输入数字，例如 1.5",
  errMaxHours: "最多 24 小时",
  errWholeNumber: "仅限整数",
  errMaxCount: "最多 999",
  errFutureDate: "日期不能是未来",
  errInvalidDate: "请输入有效日期",
  errUnexpected: "保存时出了点问题，请重试。",
  warnInstrument: "实际 + 盲飞罩时间超过白天 + 夜间时间",
  regLookingUp: "正在查询 {reg}…",
  regFound: "{reg} → {model}",
  regFromLogbook: "来自您的日志",
  regFromRegistry: "TC/FAA 注册库",
  regUse: "使用“{reg} → {model}”",
  hintRoute: "ICAO 代码，例如 CYVR-CYYZ",
  hintApproaches: "总数 — 通常为精密 + 非精密",
  hintRemarks: "Ctrl/⌘ + Enter 保存",
  takeoffsDay: "起飞 · 白天",
  takeoffsNight: "起飞 · 夜间",
  landingsDay: "着陆 · 白天",
  landingsNight: "着陆 · 夜间",
};

const es: Table = {
  newFlight: "Nuevo vuelo",
  editFlight: "Editar vuelo",
  newFlightDesc: "Registra un vuelo. Solo fecha, aeronave y tiempo son obligatorios.",
  editFlightDesc: "Los cambios se aplican a tus totales y vigencias en cuanto guardes.",
  backToFlights: "Volver a vuelos",
  sectionCrew: "Tripulación",
  timeMeta: "Décimas de hora",
  summaryTitle: "Resumen",
  totalTime: "Tiempo total",
  statInstrument: "Instrumentos",
  yes: "Sí",
  no: "No",
  readyToSave: "Listo para guardar",
  needsAttentionOne: "1 campo necesita atención",
  needsAttention: "{n} campos necesitan atención",
  saveFlight: "Guardar vuelo",
  saveChanges: "Guardar cambios",
  deleteFlight: "Eliminar vuelo",
  deleteQuestion: "¿Eliminar este vuelo?",
  deleteHelp: "Se quitará de tus totales y vigencias. No se puede deshacer.",
  confirmDelete: "Confirmar eliminación",
  keep: "Conservar",
  deleting: "Eliminando…",
  discardQuestion: "¿Descartar los cambios sin guardar?",
  discardHelp: "Tus cambios en este vuelo no se guardarán.",
  discard: "Descartar",
  discarding: "Descartando…",
  keepEditing: "Seguir editando",
  xcShort: "XC",
  errRequired: "Obligatorio",
  errEnterSomeTime: "Ingresa al menos algo de tiempo",
  errInvalidNumber: "Ingresa un número, p. ej. 1.5",
  errMaxHours: "Máx. 24 h",
  errWholeNumber: "Solo números enteros",
  errMaxCount: "Máx. 999",
  errFutureDate: "La fecha no puede ser futura",
  errInvalidDate: "Ingresa una fecha válida",
  errUnexpected: "Algo salió mal al guardar. Inténtalo de nuevo.",
  warnInstrument: "Real + capucha supera día + noche",
  regLookingUp: "Buscando {reg}…",
  regFound: "{reg} → {model}",
  regFromLogbook: "de tu bitácora",
  regFromRegistry: "registro TC/FAA",
  regUse: "Usar ‘{reg} → {model}’",
  hintRoute: "Códigos ICAO, p. ej. CYVR-CYYZ",
  hintApproaches: "Total — normalmente precisión + no precisión",
  hintRemarks: "Ctrl/⌘ + Enter para guardar",
  takeoffsDay: "Despegues · día",
  takeoffsNight: "Despegues · noche",
  landingsDay: "Aterrizajes · día",
  landingsNight: "Aterrizajes · noche",
};

const STRINGS: Record<Locale, Table> = { en, ko, zh, es };

export type FormT = (key: FormStringKey, vars?: Record<string, string | number>) => string;

/** Bound translator for the flight form; falls back to English, never to the key. */
export function formStrings(locale: Locale): FormT {
  const table = STRINGS[locale] ?? STRINGS.en;
  return (key, vars) => {
    let str: string = table[key] ?? STRINGS.en[key];
    if (vars) {
      for (const [k, v] of Object.entries(vars)) str = str.split(`{${k}}`).join(String(v));
    }
    return str;
  };
}
