import type { Locale } from "@/lib/i18n";

/**
 * Strings for the admin Traffic, Maintenance and activity-log tabs in the four
 * app locales — same pattern as admin-strings.ts (which keeps the Users,
 * Support and tab-bar keys). tsc fails on a missing key in any locale;
 * scripts/admin-i18n.test.ts checks non-empty values and placeholder parity.
 *
 * Safe to import from both Server and Client Components (no server imports).
 */
const en = {
  trafficTitle: "Admin · Traffic",
  trafficSubtitle: "Visits to the public site, counted without cookies.",
  rangeLabel: "Date range",
  rangeDays: "{days} days",
  statVisits: "Visits",
  statViews: "Page views",
  statSignups: "Signups",
  statSignupRate: "Signup rate",
  vsPrev: "vs previous {days} days",
  rateSmallBase: "Shown after 20 visits",
  chartTitle: "Daily visits",
  chartAria: "Visits and page views per day, last {days} days",
  colDay: "Day (UTC)",
  topPages: "Pages",
  topSources: "Sources",
  topCountries: "Countries",
  topDevices: "Devices",
  topCampaigns: "Campaigns",
  colPage: "Page",
  colSource: "Source",
  colCountry: "Country",
  colDevice: "Device",
  colCampaign: "Campaign",
  colShare: "Share",
  srcDirect: "Direct / none",
  srcOther: "Other",
  countryUnknown: "Unknown",
  devMobile: "Mobile",
  devTablet: "Tablet",
  devDesktop: "Desktop",
  pageNotFound: "Page not found (404)",
  pageShare: "Shared logbook link",
  trafficEmpty: "No visits recorded in this period yet.",
  trafficNote: "First-party and cookieless: public pages only, kept as daily totals. Signed-in app pages, bots, and visitors using Global Privacy Control, Do Not Track, the opt-out or an ad blocker aren't counted, so totals run lower than Vercel Analytics. A visit is an arrival from outside the site. Days are UTC.",
  signupsNote: "Signups count every new account, including ones created by an admin.",
  adminCreatedNote: "Includes {n} created by an admin.",
  optOut: "Don't count my visits from this browser",
  optOutOn: "This browser is excluded.",
  optOutOff: "This browser is counted.",
  ceilingHit: "Counting paused on {days} after the daily limit of {max} page views — possible spam.",
  trackingOff: "First-party counting is off (NEXT_PUBLIC_STATS_ENABLED). Vercel Analytics is unaffected.",
  legendCurrent: "This period",
  legendPrevious: "Previous period",
  chartPrevVisits: "Visits, previous period",
  flowTitle: "How visitors arrive",
  flowSubtitle: "Where visits come from, and the page they land on.",
  flowEmpty: "No arrivals in this period yet.",
  flowAria: "Visits flowing from {sources} to {pages}",
  flowTooltip: "{source} → {page}: {visits}",
  globeTitle: "Where visitors are",
  globeSubtitle: "Shaded by visits. Hover or tap a country for its numbers.",
  globeAria: "Globe shaded by visits across {countries}",
  globeTooltip: "{country}: {visits} · {views}",
  focusLabel: "Showing {name}",
  clearFocus: "Show all",
  maintTitle: "Admin · Maintenance",
  maintSubtitle: "Automatic clean-up, storage and admin activity.",
  autoTitle: "Automatic clean-up",
  autoSchedule: "Runs every day at 03:15 UTC and deletes records past their retention period.",
  lastRun: "Last run {when} · removed {count}",
  lastRunNever: "Hasn't run yet.",
  autoOverdue: "Overdue — the nightly clean-up hasn't run for over 36 hours.",
  autoErrors: "The last run reported errors: {rules}",
  colData: "Data",
  colKeep: "Kept for",
  colDue: "Due for deletion",
  ruleRateLimit: "Sign-in rate-limit records",
  ruleTraffic: "Traffic statistics",
  ruleStripe: "Stripe webhook receipts",
  ruleSupport: "Resolved support requests",
  ruleAudit: "Admin activity log",
  keepDays: "{n} days",
  keepMonths: "{n} months",
  runNow: "Run clean-up now",
  runTitle: "Run clean-up now?",
  runBody: "Deletes {count} records past their retention period. Open support requests are never deleted.",
  runConfirm: "Run clean-up",
  runDone: "Clean-up finished · removed {count}",
  nothingDue: "Nothing is due — everything is within its retention period.",
  dbTitle: "Database storage",
  dbUsage: "{used} of {limit} used (Supabase Free plan)",
  colTable: "Table",
  colSize: "Size",
  colRows: "Rows (approx.)",
  healthTitle: "Data integrity",
  healthAuthNoProfile: "{n} sign-ins have no profile and are hidden from Users.",
  healthProfileNoAuth: "{n} profiles have no sign-in.",
  healthUserCap: "Only the first 1,000 accounts are loaded — lists are truncated.",
  healthAllGood: "All good",
  purgeTitle: "Manual clean-up",
  purgeSupport: "Delete resolved support requests",
  purgeTraffic: "Delete traffic statistics",
  olderThan: "Older than {days} days",
  resolvedOlderThan: "Resolved more than {days} days ago",
  purgeAll: "All",
  purgeButton: "Delete…",
  purgeTitleSupport: "Delete {n} resolved support requests?",
  purgeTitleTraffic: "Delete traffic statistics for {n} days?",
  purgeBody: "This can't be undone and is recorded in the admin activity log. Open support requests are never deleted.",
  purgeNone: "Nothing matches — there's nothing to delete.",
  purgeDone: "Deleted · {n}",
  errFloor: "That range isn't allowed.",
  errForbidden: "Admin access required.",
  errGeneric: "Something went wrong. Try again.",
  auditTitle: "Recent admin activity",
  auditEmpty: "No admin activity recorded yet.",
  auditScheduled: "Scheduled job",
  auditFormerUser: "Former admin",
  colWhen: "When",
  colWho: "Who",
  colAction: "Action",
  colDetails: "Details",
  actHousekeepingManual: "Clean-up run by hand",
  actTrafficPurge: "Deleted traffic statistics",
  actSupportPurge: "Deleted resolved support requests",
  actSupportResolve: "Resolved a support request",
  actSupportReopen: "Reopened a support request",
  actSupportDelete: "Deleted a support request",
  actUserCreate: "Created an account",
  actUserDelete: "Deleted an account",
  actUserAdmin: "Changed admin access",
  actUserPassword: "Reset a password",
  actUserTier: "Changed a tier",
  actUserName: "Renamed an account",
  // added at integration
  globeKeys: "Arrow keys turn the globe.",
  globeReset: "Reset view",
  chartSeries: "Show or hide series",
  purgeConfirm: "Delete",
  runBodyOne: "Deletes 1 record past its retention period. Open support requests are never deleted.",
  purgeTitleSupportOne: "Delete 1 resolved support request?",
  purgeTitleTrafficOne: "Delete traffic statistics for 1 day?",
  healthAuthNoProfileOne: "1 sign-in has no profile and is hidden from Users.",
  healthProfileNoAuthOne: "1 profile has no sign-in.",
  flowHint: "Select a source or page to focus it.",
  countVisitsOne: "{n} visit",
  countVisitsOther: "{n} visits",
  countViewsOne: "{n} page view",
  countViewsOther: "{n} page views",
  countSourcesOne: "{n} source",
  countSourcesOther: "{n} sources",
  countPagesOne: "{n} landing page",
  countPagesOther: "{n} landing pages",
  countCountriesOne: "{n} country",
  countCountriesOther: "{n} countries",
  optOutSignal: "Your browser's privacy signal (Global Privacy Control or Do Not Track) is on, so this browser isn't counted.",
} as const;

export type AdminOpsKey = keyof typeof en;
type Table = Record<AdminOpsKey, string>;

/** Every key, for scripts/admin-i18n.test.ts. */
export const ADMIN_OPS_KEYS = Object.keys(en) as AdminOpsKey[];

const ko: Table = {
  trafficTitle: "관리자 · 트래픽",
  trafficSubtitle: "쿠키 없이 집계한 공개 사이트 방문 수입니다.",
  rangeLabel: "기간",
  rangeDays: "{days}일",
  statVisits: "방문",
  statViews: "페이지뷰",
  statSignups: "가입",
  statSignupRate: "가입률",
  vsPrev: "이전 {days}일 대비",
  rateSmallBase: "방문 20회 이후 표시",
  chartTitle: "일별 방문",
  chartAria: "최근 {days}일간 일별 방문 및 페이지뷰",
  colDay: "날짜 (UTC)",
  topPages: "페이지",
  topSources: "유입 경로",
  topCountries: "국가",
  topDevices: "기기",
  topCampaigns: "캠페인",
  colPage: "페이지",
  colSource: "유입 경로",
  colCountry: "국가",
  colDevice: "기기",
  colCampaign: "캠페인",
  colShare: "비율",
  srcDirect: "직접 방문 / 없음",
  srcOther: "기타",
  countryUnknown: "알 수 없음",
  devMobile: "모바일",
  devTablet: "태블릿",
  devDesktop: "데스크톱",
  pageNotFound: "페이지 없음 (404)",
  pageShare: "공유된 로그북 링크",
  trafficEmpty: "이 기간에 기록된 방문이 없습니다.",
  trafficNote: "자체 수집, 쿠키 없음: 공개 페이지만 일별 합계로 보관합니다. 로그인 후 앱 페이지, 봇, Global Privacy Control·Do Not Track·수집 거부·광고 차단기를 사용하는 방문자는 집계하지 않으므로 Vercel Analytics보다 수치가 낮습니다. 방문은 사이트 외부에서 들어온 경우를 뜻합니다. 날짜는 UTC 기준입니다.",
  signupsNote: "가입 수에는 관리자가 만든 계정을 포함한 모든 신규 계정이 포함됩니다.",
  adminCreatedNote: "관리자가 만든 {n}개 포함.",
  optOut: "이 브라우저의 내 방문은 집계하지 않기",
  optOutOn: "이 브라우저는 제외되었습니다.",
  optOutOff: "이 브라우저는 집계됩니다.",
  ceilingHit: "{days}에 일일 한도({max} 페이지뷰)에 도달해 집계가 중단되었습니다 — 스팸일 수 있습니다.",
  trackingOff: "자체 집계가 꺼져 있습니다 (NEXT_PUBLIC_STATS_ENABLED). Vercel Analytics에는 영향이 없습니다.",
  legendCurrent: "이번 기간",
  legendPrevious: "이전 기간",
  chartPrevVisits: "이전 기간 방문",
  flowTitle: "방문 유입 흐름",
  flowSubtitle: "방문이 어디에서 와서 어떤 페이지에 도착하는지 보여 줍니다.",
  flowEmpty: "이 기간에 유입된 방문이 없습니다.",
  flowAria: "{sources}에서 {pages}(으)로 이어지는 방문 흐름",
  flowTooltip: "{source} → {page}: {visits}",
  globeTitle: "방문자 위치",
  globeSubtitle: "방문 수에 따라 색칠됩니다. 국가에 마우스를 올리거나 탭하면 수치가 표시됩니다.",
  globeAria: "{countries}의 방문 수로 색칠된 지구본",
  globeTooltip: "{country}: {visits} · {views}",
  focusLabel: "{name} 표시 중",
  clearFocus: "전체 보기",
  maintTitle: "관리자 · 유지 관리",
  maintSubtitle: "자동 정리, 저장 공간, 관리자 활동.",
  autoTitle: "자동 정리",
  autoSchedule: "매일 03:15 UTC에 실행되어 보관 기간이 지난 기록을 삭제합니다.",
  lastRun: "마지막 실행 {when} · {count}건 삭제",
  lastRunNever: "아직 실행되지 않았습니다.",
  autoOverdue: "지연됨 — 야간 정리가 36시간 넘게 실행되지 않았습니다.",
  autoErrors: "마지막 실행에서 오류가 발생했습니다: {rules}",
  colData: "데이터",
  colKeep: "보관 기간",
  colDue: "삭제 대상",
  ruleRateLimit: "로그인 시도 제한 기록",
  ruleTraffic: "트래픽 통계",
  ruleStripe: "Stripe 웹훅 수신 기록",
  ruleSupport: "해결된 지원 요청",
  ruleAudit: "관리자 활동 기록",
  keepDays: "{n}일",
  keepMonths: "{n}개월",
  runNow: "지금 정리 실행",
  runTitle: "지금 정리를 실행할까요?",
  runBody: "보관 기간이 지난 기록 {count}건을 삭제합니다. 미해결 지원 요청은 삭제되지 않습니다.",
  runConfirm: "정리 실행",
  runDone: "정리 완료 · {count}건 삭제",
  nothingDue: "삭제 대상이 없습니다 — 모두 보관 기간 이내입니다.",
  dbTitle: "데이터베이스 저장 공간",
  dbUsage: "{limit} 중 {used} 사용 (Supabase 무료 플랜)",
  colTable: "테이블",
  colSize: "크기",
  colRows: "행 (대략)",
  healthTitle: "데이터 무결성",
  healthAuthNoProfile: "프로필이 없는 로그인 {n}개가 사용자 목록에서 숨겨져 있습니다.",
  healthProfileNoAuth: "로그인이 없는 프로필 {n}개.",
  healthUserCap: "처음 1,000개 계정만 불러옵니다 — 목록이 잘렸습니다.",
  healthAllGood: "이상 없음",
  purgeTitle: "수동 정리",
  purgeSupport: "해결된 지원 요청 삭제",
  purgeTraffic: "트래픽 통계 삭제",
  olderThan: "{days}일 이전",
  resolvedOlderThan: "{days}일 이전에 해결됨",
  purgeAll: "전체",
  purgeButton: "삭제…",
  purgeTitleSupport: "해결된 지원 요청 {n}건을 삭제할까요?",
  purgeTitleTraffic: "{n}일치 트래픽 통계를 삭제할까요?",
  purgeBody: "되돌릴 수 없으며 관리자 활동 기록에 남습니다. 미해결 지원 요청은 삭제되지 않습니다.",
  purgeNone: "일치하는 항목이 없어 삭제할 것이 없습니다.",
  purgeDone: "삭제됨 · {n}",
  errFloor: "허용되지 않는 범위입니다.",
  errForbidden: "관리자 권한이 필요합니다.",
  errGeneric: "문제가 발생했습니다. 다시 시도하세요.",
  auditTitle: "최근 관리자 활동",
  auditEmpty: "기록된 관리자 활동이 없습니다.",
  auditScheduled: "예약 작업",
  auditFormerUser: "이전 관리자",
  colWhen: "시간",
  colWho: "작업자",
  colAction: "작업",
  colDetails: "세부 정보",
  actHousekeepingManual: "수동 정리 실행",
  actTrafficPurge: "트래픽 통계 삭제",
  actSupportPurge: "해결된 지원 요청 삭제",
  actSupportResolve: "지원 요청 해결",
  actSupportReopen: "지원 요청 다시 열기",
  actSupportDelete: "지원 요청 1건 삭제",
  actUserCreate: "계정 생성",
  actUserDelete: "계정 삭제",
  actUserAdmin: "관리자 권한 변경",
  actUserPassword: "비밀번호 재설정",
  actUserTier: "등급 변경",
  actUserName: "계정 이름 변경",
  globeKeys: "화살표 키로 지구본을 돌릴 수 있습니다.",
  globeReset: "보기 초기화",
  chartSeries: "표시할 데이터 선택",
  purgeConfirm: "삭제",
  runBodyOne: "보관 기간이 지난 기록 1건을 삭제합니다. 미해결 지원 요청은 삭제되지 않습니다.",
  purgeTitleSupportOne: "해결된 지원 요청 1건을 삭제할까요?",
  purgeTitleTrafficOne: "1일치 트래픽 통계를 삭제할까요?",
  healthAuthNoProfileOne: "프로필이 없는 로그인 1개가 사용자 목록에서 숨겨져 있습니다.",
  healthProfileNoAuthOne: "로그인이 없는 프로필 1개.",
  flowHint: "유입 경로나 페이지를 선택하면 강조됩니다.",
  countVisitsOne: "방문 {n}회",
  countVisitsOther: "방문 {n}회",
  countViewsOne: "페이지뷰 {n}회",
  countViewsOther: "페이지뷰 {n}회",
  countSourcesOne: "유입 경로 {n}개",
  countSourcesOther: "유입 경로 {n}개",
  countPagesOne: "도착 페이지 {n}개",
  countPagesOther: "도착 페이지 {n}개",
  countCountriesOne: "{n}개 국가",
  countCountriesOther: "{n}개 국가",
  optOutSignal: "브라우저의 개인정보 보호 신호(Global Privacy Control 또는 Do Not Track)가 켜져 있어 이 브라우저는 집계되지 않습니다.",
};

const zh: Table = {
  trafficTitle: "管理员 · 流量",
  trafficSubtitle: "公开网站的访问量，不使用 Cookie 统计。",
  rangeLabel: "时间范围",
  rangeDays: "{days} 天",
  statVisits: "访问",
  statViews: "页面浏览量",
  statSignups: "注册",
  statSignupRate: "注册率",
  vsPrev: "较前 {days} 天",
  rateSmallBase: "访问满 20 次后显示",
  chartTitle: "每日访问",
  chartAria: "最近 {days} 天每日访问量和页面浏览量",
  colDay: "日期 (UTC)",
  topPages: "页面",
  topSources: "来源",
  topCountries: "国家/地区",
  topDevices: "设备",
  topCampaigns: "推广活动",
  colPage: "页面",
  colSource: "来源",
  colCountry: "国家/地区",
  colDevice: "设备",
  colCampaign: "推广活动",
  colShare: "占比",
  srcDirect: "直接访问 / 无",
  srcOther: "其他",
  countryUnknown: "未知",
  devMobile: "手机",
  devTablet: "平板",
  devDesktop: "桌面",
  pageNotFound: "页面不存在 (404)",
  pageShare: "共享的飞行日志链接",
  trafficEmpty: "此期间尚无访问记录。",
  trafficNote: "自有统计、不使用 Cookie：仅统计公开页面，只保存每日总数。登录后的应用页面、机器人，以及启用 Global Privacy Control、Do Not Track、退出统计或广告拦截器的访客不计入，因此数字低于 Vercel Analytics。“访问”指从站外进入本站。日期按 UTC 计算。",
  signupsNote: "注册数包含所有新账户，包括管理员创建的账户。",
  adminCreatedNote: "包含管理员创建的 {n} 个。",
  optOut: "不统计我在此浏览器上的访问",
  optOutOn: "此浏览器已排除。",
  optOutOff: "此浏览器会被统计。",
  ceilingHit: "{days} 达到每日 {max} 次页面浏览上限，已暂停统计 — 可能是垃圾流量。",
  trackingOff: "自有统计已关闭（NEXT_PUBLIC_STATS_ENABLED）。Vercel Analytics 不受影响。",
  legendCurrent: "本期",
  legendPrevious: "上一期",
  chartPrevVisits: "上一期访问",
  flowTitle: "访客来源流向",
  flowSubtitle: "访问来自哪里、落在哪个页面。",
  flowEmpty: "此期间尚无访问进入。",
  flowAria: "访问从{sources}流向{pages}",
  flowTooltip: "{source} → {page}：{visits}",
  globeTitle: "访客所在地",
  globeSubtitle: "颜色深浅表示访问量。悬停或点按国家/地区可查看数字。",
  globeAria: "按{countries}的访问量着色的地球",
  globeTooltip: "{country}：{visits} · {views}",
  focusLabel: "正在显示：{name}",
  clearFocus: "显示全部",
  maintTitle: "管理员 · 维护",
  maintSubtitle: "自动清理、存储空间和管理员操作记录。",
  autoTitle: "自动清理",
  autoSchedule: "每天 03:15（UTC）运行，删除超过保留期限的记录。",
  lastRun: "上次运行 {when} · 删除 {count} 条",
  lastRunNever: "尚未运行。",
  autoOverdue: "已逾期 — 夜间清理已超过 36 小时未运行。",
  autoErrors: "上次运行报告了错误：{rules}",
  colData: "数据",
  colKeep: "保留期限",
  colDue: "待删除",
  ruleRateLimit: "登录频率限制记录",
  ruleTraffic: "流量统计",
  ruleStripe: "Stripe Webhook 接收记录",
  ruleSupport: "已解决的支持请求",
  ruleAudit: "管理员操作日志",
  keepDays: "{n} 天",
  keepMonths: "{n} 个月",
  runNow: "立即清理",
  runTitle: "立即运行清理？",
  runBody: "将删除 {count} 条超过保留期限的记录。待处理的支持请求永远不会被删除。",
  runConfirm: "运行清理",
  runDone: "清理完成 · 删除 {count} 条",
  nothingDue: "没有待删除的内容 — 所有记录都在保留期限内。",
  dbTitle: "数据库存储",
  dbUsage: "已使用 {used} / {limit}（Supabase 免费套餐）",
  colTable: "数据表",
  colSize: "大小",
  colRows: "行数（约）",
  healthTitle: "数据完整性",
  healthAuthNoProfile: "有 {n} 个登录账户没有资料，未在用户列表中显示。",
  healthProfileNoAuth: "有 {n} 个资料没有对应的登录账户。",
  healthUserCap: "仅加载前 1,000 个账户 — 列表已截断。",
  healthAllGood: "一切正常",
  purgeTitle: "手动清理",
  purgeSupport: "删除已解决的支持请求",
  purgeTraffic: "删除流量统计",
  olderThan: "早于 {days} 天",
  resolvedOlderThan: "{days} 天前已解决",
  purgeAll: "全部",
  purgeButton: "删除…",
  purgeTitleSupport: "删除 {n} 条已解决的支持请求？",
  purgeTitleTraffic: "删除 {n} 天的流量统计？",
  purgeBody: "此操作无法撤销，并会记录在管理员操作日志中。待处理的支持请求永远不会被删除。",
  purgeNone: "没有匹配的记录，无需删除。",
  purgeDone: "已删除 · {n}",
  errFloor: "不允许该范围。",
  errForbidden: "需要管理员权限。",
  errGeneric: "出了点问题，请重试。",
  auditTitle: "最近的管理员操作",
  auditEmpty: "尚无管理员操作记录。",
  auditScheduled: "定时任务",
  auditFormerUser: "已删除的管理员",
  colWhen: "时间",
  colWho: "操作人",
  colAction: "操作",
  colDetails: "详情",
  actHousekeepingManual: "手动运行清理",
  actTrafficPurge: "删除了流量统计",
  actSupportPurge: "删除了已解决的支持请求",
  actSupportResolve: "解决了一条支持请求",
  actSupportReopen: "重新打开了一条支持请求",
  actSupportDelete: "删除了一条支持请求",
  actUserCreate: "创建了账户",
  actUserDelete: "删除了账户",
  actUserAdmin: "更改了管理员权限",
  actUserPassword: "重置了密码",
  actUserTier: "更改了级别",
  actUserName: "更改了账户名称",
  globeKeys: "使用方向键旋转地球仪。",
  globeReset: "重置视图",
  chartSeries: "显示或隐藏数据系列",
  purgeConfirm: "删除",
  runBodyOne: "将删除 1 条超过保留期限的记录。待处理的支持请求永远不会被删除。",
  purgeTitleSupportOne: "删除 1 条已解决的支持请求？",
  purgeTitleTrafficOne: "删除 1 天的流量统计？",
  healthAuthNoProfileOne: "有 1 个登录账户没有资料，未在用户列表中显示。",
  healthProfileNoAuthOne: "有 1 个资料没有对应的登录账户。",
  flowHint: "选择来源或页面即可聚焦。",
  countVisitsOne: "{n} 次访问",
  countVisitsOther: "{n} 次访问",
  countViewsOne: "{n} 次页面浏览",
  countViewsOther: "{n} 次页面浏览",
  countSourcesOne: "{n} 个来源",
  countSourcesOther: "{n} 个来源",
  countPagesOne: "{n} 个落地页面",
  countPagesOther: "{n} 个落地页面",
  countCountriesOne: "{n} 个国家/地区",
  countCountriesOther: "{n} 个国家/地区",
  optOutSignal: "您的浏览器已开启隐私信号（Global Privacy Control 或 Do Not Track），因此不会统计此浏览器。",
};

const es: Table = {
  trafficTitle: "Admin · Tráfico",
  trafficSubtitle: "Visitas al sitio público, contadas sin cookies.",
  rangeLabel: "Periodo",
  rangeDays: "{days} días",
  statVisits: "Visitas",
  statViews: "Páginas vistas",
  statSignups: "Registros",
  statSignupRate: "Tasa de registro",
  vsPrev: "vs. {days} días anteriores",
  rateSmallBase: "Se muestra a partir de 20 visitas",
  chartTitle: "Visitas diarias",
  chartAria: "Visitas y páginas vistas por día, últimos {days} días",
  colDay: "Día (UTC)",
  topPages: "Páginas",
  topSources: "Fuentes",
  topCountries: "Países",
  topDevices: "Dispositivos",
  topCampaigns: "Campañas",
  colPage: "Página",
  colSource: "Fuente",
  colCountry: "País",
  colDevice: "Dispositivo",
  colCampaign: "Campaña",
  colShare: "Proporción",
  srcDirect: "Directo / ninguno",
  srcOther: "Otros",
  countryUnknown: "Desconocido",
  devMobile: "Móvil",
  devTablet: "Tableta",
  devDesktop: "Escritorio",
  pageNotFound: "Página no encontrada (404)",
  pageShare: "Enlace de bitácora compartida",
  trafficEmpty: "Aún no hay visitas registradas en este periodo.",
  trafficNote: "Propio y sin cookies: solo páginas públicas, guardadas como totales diarios. No se cuentan las páginas de la app con sesión iniciada, los bots ni los visitantes con Global Privacy Control, Do Not Track, la exclusión voluntaria o un bloqueador de anuncios, así que las cifras son menores que en Vercel Analytics. Una visita es una llegada desde fuera del sitio. Los días están en UTC.",
  signupsNote: "Los registros incluyen todas las cuentas nuevas, también las creadas por un administrador.",
  adminCreatedNote: "Incluye {n} creadas por un administrador.",
  optOut: "No contar mis visitas desde este navegador",
  optOutOn: "Este navegador está excluido.",
  optOutOff: "Este navegador se cuenta.",
  ceilingHit: "Conteo pausado el {days} al alcanzar el límite diario de {max} páginas vistas — posible spam.",
  trackingOff: "El conteo propio está desactivado (NEXT_PUBLIC_STATS_ENABLED). Vercel Analytics no se ve afectado.",
  legendCurrent: "Este periodo",
  legendPrevious: "Periodo anterior",
  chartPrevVisits: "Visitas, periodo anterior",
  flowTitle: "Cómo llegan los visitantes",
  flowSubtitle: "De dónde llegan las visitas y en qué página aterrizan.",
  flowEmpty: "Aún no hay llegadas en este periodo.",
  flowAria: "Visitas que fluyen de {sources} a {pages}",
  flowTooltip: "{source} → {page}: {visits}",
  globeTitle: "Dónde están los visitantes",
  globeSubtitle: "Sombreado según las visitas. Pasa el cursor o toca un país para ver sus cifras.",
  globeAria: "Globo sombreado por visitas en {countries}",
  globeTooltip: "{country}: {visits} · {views}",
  focusLabel: "Mostrando {name}",
  clearFocus: "Mostrar todo",
  maintTitle: "Admin · Mantenimiento",
  maintSubtitle: "Limpieza automática, almacenamiento y actividad de administración.",
  autoTitle: "Limpieza automática",
  autoSchedule: "Se ejecuta cada día a las 03:15 UTC y elimina los registros que superan su periodo de conservación.",
  lastRun: "Última ejecución {when} · {count} eliminados",
  lastRunNever: "Aún no se ha ejecutado.",
  autoOverdue: "Atrasada: la limpieza nocturna lleva más de 36 horas sin ejecutarse.",
  autoErrors: "La última ejecución informó errores: {rules}",
  colData: "Datos",
  colKeep: "Se conserva",
  colDue: "Pendiente de eliminar",
  ruleRateLimit: "Registros de límite de inicio de sesión",
  ruleTraffic: "Estadísticas de tráfico",
  ruleStripe: "Recibos de webhooks de Stripe",
  ruleSupport: "Solicitudes de soporte resueltas",
  ruleAudit: "Registro de actividad de administración",
  keepDays: "{n} días",
  keepMonths: "{n} meses",
  runNow: "Limpiar ahora",
  runTitle: "¿Ejecutar la limpieza ahora?",
  runBody: "Elimina {count} registros que superan su periodo de conservación. Las solicitudes de soporte abiertas nunca se eliminan.",
  runConfirm: "Ejecutar limpieza",
  runDone: "Limpieza terminada · {count} eliminados",
  nothingDue: "No hay nada pendiente: todo está dentro de su periodo de conservación.",
  dbTitle: "Almacenamiento de la base de datos",
  dbUsage: "{used} de {limit} usados (plan gratuito de Supabase)",
  colTable: "Tabla",
  colSize: "Tamaño",
  colRows: "Filas (aprox.)",
  healthTitle: "Integridad de datos",
  healthAuthNoProfile: "{n} cuentas de acceso no tienen perfil y no aparecen en Usuarios.",
  healthProfileNoAuth: "{n} perfiles no tienen cuenta de acceso.",
  healthUserCap: "Solo se cargan las primeras 1000 cuentas: las listas están truncadas.",
  healthAllGood: "Todo bien",
  purgeTitle: "Limpieza manual",
  purgeSupport: "Eliminar solicitudes de soporte resueltas",
  purgeTraffic: "Eliminar estadísticas de tráfico",
  olderThan: "Con más de {days} días",
  resolvedOlderThan: "Resueltas hace más de {days} días",
  purgeAll: "Todo",
  purgeButton: "Eliminar…",
  purgeTitleSupport: "¿Eliminar {n} solicitudes de soporte resueltas?",
  purgeTitleTraffic: "¿Eliminar las estadísticas de tráfico de {n} días?",
  purgeBody: "No se puede deshacer y queda registrado en la actividad de administración. Las solicitudes de soporte abiertas nunca se eliminan.",
  purgeNone: "No hay coincidencias: no hay nada que eliminar.",
  purgeDone: "Eliminado · {n}",
  errFloor: "Ese intervalo no está permitido.",
  errForbidden: "Se requiere acceso de administrador.",
  errGeneric: "Algo salió mal. Inténtalo de nuevo.",
  auditTitle: "Actividad reciente de administración",
  auditEmpty: "Aún no hay actividad de administración registrada.",
  auditScheduled: "Tarea programada",
  auditFormerUser: "Antiguo administrador",
  colWhen: "Cuándo",
  colWho: "Quién",
  colAction: "Acción",
  colDetails: "Detalles",
  actHousekeepingManual: "Limpieza ejecutada manualmente",
  actTrafficPurge: "Eliminó estadísticas de tráfico",
  actSupportPurge: "Eliminó solicitudes de soporte resueltas",
  actSupportResolve: "Resolvió una solicitud de soporte",
  actSupportReopen: "Reabrió una solicitud de soporte",
  actSupportDelete: "Eliminó una solicitud de soporte",
  actUserCreate: "Creó una cuenta",
  actUserDelete: "Eliminó una cuenta",
  actUserAdmin: "Cambió el acceso de administrador",
  actUserPassword: "Restableció una contraseña",
  actUserTier: "Cambió un nivel",
  actUserName: "Cambió el nombre de una cuenta",
  globeKeys: "Usa las flechas del teclado para girar el globo.",
  globeReset: "Restablecer vista",
  chartSeries: "Mostrar u ocultar series",
  purgeConfirm: "Eliminar",
  runBodyOne: "Elimina 1 registro que supera su periodo de conservación. Las solicitudes de soporte abiertas nunca se eliminan.",
  purgeTitleSupportOne: "¿Eliminar 1 solicitud de soporte resuelta?",
  purgeTitleTrafficOne: "¿Eliminar las estadísticas de tráfico de 1 día?",
  healthAuthNoProfileOne: "1 cuenta de acceso no tiene perfil y no aparece en Usuarios.",
  healthProfileNoAuthOne: "1 perfil no tiene cuenta de acceso.",
  flowHint: "Selecciona una fuente o página para destacarla.",
  countVisitsOne: "{n} visita",
  countVisitsOther: "{n} visitas",
  countViewsOne: "{n} página vista",
  countViewsOther: "{n} páginas vistas",
  countSourcesOne: "{n} fuente",
  countSourcesOther: "{n} fuentes",
  countPagesOne: "{n} página de llegada",
  countPagesOther: "{n} páginas de llegada",
  countCountriesOne: "{n} país",
  countCountriesOther: "{n} países",
  optOutSignal: "La señal de privacidad de tu navegador (Global Privacy Control o Do Not Track) está activada, así que este navegador no se cuenta.",
};

const STRINGS: Record<Locale, Table> = { en, ko, zh, es };

export type AdminOpsT = (key: AdminOpsKey, vars?: Record<string, string | number>) => string;

/** Bound translator; falls back to English, never to the key. */
export function adminOpsStrings(locale: Locale): AdminOpsT {
  const table = STRINGS[locale] ?? STRINGS.en;
  return (key, vars) => {
    let str: string = table[key] ?? STRINGS.en[key];
    if (vars) {
      for (const [k, v] of Object.entries(vars)) str = str.split(`{${k}}`).join(String(v));
    }
    return str;
  };
}
