import type { Locale } from "@/lib/i18n";

/**
 * Strings for the admin user-management page in the four app locales. Kept
 * local (same pattern as app/app/flights/form-strings.ts) so lib/i18n.ts
 * doesn't churn; fold them in later.
 *
 * Safe to import from both Server and Client Components (no server imports).
 */
const en = {
  title: "Admin · Users",
  subtitle: "Every account, with tier and admin controls.",
  statTotal: "Users",
  statFree: "Free",
  statPro: "Pro",
  statLifetime: "Lifetime",
  search: "Search users",
  searchPh: "Search by email or name…",
  createUser: "Create user",
  createTitle: "Create new user",
  createDesc: "The account is auto-confirmed — the user can sign in immediately with the temporary password we generate.",
  email: "Email",
  password: "Password",
  signIn: "Sign in",
  fullName: "Full name",
  tier: "Tier",
  tierFree: "Free",
  tierPro: "Pro",
  tierLifetime: "Lifetime",
  creating: "Creating…",
  created: "Account created",
  createdBody: "Share these credentials with {email} securely (password manager or encrypted message). They should change the password on first sign-in.",
  tempPassword: "Temporary password",
  copyCredentials: "Copy credentials",
  credentialsCopied: "Credentials copied",
  copyFailed: "Couldn't copy — select the text and copy it manually.",
  dismiss: "Dismiss",
  colEmail: "Email",
  colName: "Name",
  colTier: "Tier",
  colRegime: "Regime",
  colStripe: "Stripe",
  colAdmin: "Admin",
  colSignedUp: "Signed up",
  colLastSeen: "Last active",
  colActions: "Actions",
  noMatch: "No users match “{q}”.",
  noUsers: "No users yet.",
  editName: "Edit name for {email}",
  nameLabel: "Name",
  save: "Save",
  cancel: "Cancel",
  nameSaved: "Name updated",
  tierLabel: "Tier for {email}",
  tierUpdated: "Tier set to {tier}",
  stripeLinked: "Stripe customer linked",
  stripeNone: "No Stripe customer",
  isAdmin: "Admin",
  notAdmin: "Not an admin",
  grantAdmin: "Grant admin to {email}",
  revokeAdmin: "Revoke admin from {email}",
  grantTitle: "Grant admin to {email}?",
  grantBody: "Admins can view and edit every user, including tiers and passwords.",
  grantConfirm: "Grant admin",
  revokeTitle: "Remove admin from {email}?",
  revokeBody: "They keep their account and flights, but lose access to this page.",
  revokeConfirm: "Remove admin",
  adminGranted: "Admin granted",
  adminRevoked: "Admin removed",
  resetPw: "Reset password",
  resetTitle: "Reset the password for {email}?",
  resetBody: "Their current password stops working immediately. You'll get a new temporary password to share with them.",
  resetConfirm: "Generate new password",
  resetDone: "Password reset",
  resetDoneBody: "New password for {email} — share it securely. They should change it on first sign-in.",
  deleteUser: "Delete",
  deleteArmTitle: "Delete {email}?",
  deleteArmBody: "This wipes their account, flights, documents and files. There is no undo. Type the email to continue.",
  deleteTypeLabel: "Type the email to confirm",
  deleteContinue: "Delete permanently",
  deleteTitle: "Permanently delete {email}?",
  deleteBody: "Their sign-in, profile, flights, documents and uploaded files are removed. This cannot be undone.",
  deleteConfirm: "Delete account",
  deleted: "Account deleted",
  deletedBody: "{email} and all their data are gone.",
  errNetwork: "Network error — try again. Your connection may be flaky.",
  errUnexpected: "Something went wrong. Try again.",
  errEmail: "Enter a valid email address",
} as const;

export type AdminStringKey = keyof typeof en;
type Table = Record<AdminStringKey, string>;

const ko: Table = {
  title: "관리자 · 사용자",
  subtitle: "모든 계정과 등급, 관리자 권한을 관리합니다.",
  statTotal: "사용자",
  statFree: "무료",
  statPro: "Pro",
  statLifetime: "평생",
  search: "사용자 검색",
  searchPh: "이메일 또는 이름으로 검색…",
  createUser: "사용자 생성",
  createTitle: "새 사용자 생성",
  createDesc: "계정은 자동으로 확인됩니다 — 사용자는 생성된 임시 비밀번호로 바로 로그인할 수 있습니다.",
  email: "이메일",
  password: "비밀번호",
  signIn: "로그인",
  fullName: "이름",
  tier: "등급",
  tierFree: "무료",
  tierPro: "Pro",
  tierLifetime: "평생",
  creating: "생성 중…",
  created: "계정이 생성되었습니다",
  createdBody: "이 자격 증명을 {email}에게 안전하게 전달하세요 (비밀번호 관리자 또는 암호화된 메시지). 첫 로그인 시 비밀번호를 변경해야 합니다.",
  tempPassword: "임시 비밀번호",
  copyCredentials: "자격 증명 복사",
  credentialsCopied: "자격 증명이 복사되었습니다",
  copyFailed: "복사할 수 없습니다 — 텍스트를 선택해 직접 복사하세요.",
  dismiss: "닫기",
  colEmail: "이메일",
  colName: "이름",
  colTier: "등급",
  colRegime: "규제 체계",
  colStripe: "Stripe",
  colAdmin: "관리자",
  colSignedUp: "가입일",
  colLastSeen: "마지막 활동",
  colActions: "작업",
  noMatch: "“{q}”과(와) 일치하는 사용자가 없습니다.",
  noUsers: "아직 사용자가 없습니다.",
  editName: "{email}의 이름 편집",
  nameLabel: "이름",
  save: "저장",
  cancel: "취소",
  nameSaved: "이름이 업데이트되었습니다",
  tierLabel: "{email}의 등급",
  tierUpdated: "등급이 {tier}(으)로 설정되었습니다",
  stripeLinked: "Stripe 고객 연결됨",
  stripeNone: "Stripe 고객 없음",
  isAdmin: "관리자",
  notAdmin: "관리자 아님",
  grantAdmin: "{email}에게 관리자 권한 부여",
  revokeAdmin: "{email}의 관리자 권한 해제",
  grantTitle: "{email}에게 관리자 권한을 부여할까요?",
  grantBody: "관리자는 등급과 비밀번호를 포함해 모든 사용자를 보고 편집할 수 있습니다.",
  grantConfirm: "관리자 권한 부여",
  revokeTitle: "{email}의 관리자 권한을 해제할까요?",
  revokeBody: "계정과 비행 기록은 유지되지만 이 페이지에는 접근할 수 없게 됩니다.",
  revokeConfirm: "관리자 권한 해제",
  adminGranted: "관리자 권한이 부여되었습니다",
  adminRevoked: "관리자 권한이 해제되었습니다",
  resetPw: "비밀번호 재설정",
  resetTitle: "{email}의 비밀번호를 재설정할까요?",
  resetBody: "현재 비밀번호는 즉시 사용할 수 없게 됩니다. 전달할 새 임시 비밀번호가 발급됩니다.",
  resetConfirm: "새 비밀번호 생성",
  resetDone: "비밀번호가 재설정되었습니다",
  resetDoneBody: "{email}의 새 비밀번호 — 안전하게 전달하세요. 첫 로그인 시 변경해야 합니다.",
  deleteUser: "삭제",
  deleteArmTitle: "{email}을(를) 삭제할까요?",
  deleteArmBody: "계정, 비행, 문서, 파일이 모두 삭제됩니다. 되돌릴 수 없습니다. 계속하려면 이메일을 입력하세요.",
  deleteTypeLabel: "확인을 위해 이메일 입력",
  deleteContinue: "영구 삭제",
  deleteTitle: "{email}을(를) 영구 삭제할까요?",
  deleteBody: "로그인 정보, 프로필, 비행, 문서, 업로드한 파일이 삭제됩니다. 되돌릴 수 없습니다.",
  deleteConfirm: "계정 삭제",
  deleted: "계정이 삭제되었습니다",
  deletedBody: "{email}과(와) 모든 데이터가 삭제되었습니다.",
  errNetwork: "네트워크 오류 — 다시 시도하세요. 연결이 불안정할 수 있습니다.",
  errUnexpected: "문제가 발생했습니다. 다시 시도하세요.",
  errEmail: "올바른 이메일 주소를 입력하세요",
};

const zh: Table = {
  title: "管理员 · 用户",
  subtitle: "所有账户及其级别与管理员权限。",
  statTotal: "用户",
  statFree: "免费",
  statPro: "Pro",
  statLifetime: "终身",
  search: "搜索用户",
  searchPh: "按邮箱或姓名搜索…",
  createUser: "创建用户",
  createTitle: "创建新用户",
  createDesc: "账户自动确认——用户可立即使用我们生成的临时密码登录。",
  email: "邮箱",
  password: "密码",
  signIn: "登录",
  fullName: "姓名",
  tier: "级别",
  tierFree: "免费",
  tierPro: "Pro",
  tierLifetime: "终身",
  creating: "正在创建…",
  created: "账户已创建",
  createdBody: "请通过安全方式（密码管理器或加密消息）将这些凭据分享给 {email}。他们应在首次登录时修改密码。",
  tempPassword: "临时密码",
  copyCredentials: "复制凭据",
  credentialsCopied: "凭据已复制",
  copyFailed: "无法复制——请选中文本后手动复制。",
  dismiss: "关闭",
  colEmail: "邮箱",
  colName: "姓名",
  colTier: "级别",
  colRegime: "监管体系",
  colStripe: "Stripe",
  colAdmin: "管理员",
  colSignedUp: "注册时间",
  colLastSeen: "最近活跃",
  colActions: "操作",
  noMatch: "没有与“{q}”匹配的用户。",
  noUsers: "还没有用户。",
  editName: "编辑 {email} 的姓名",
  nameLabel: "姓名",
  save: "保存",
  cancel: "取消",
  nameSaved: "姓名已更新",
  tierLabel: "{email} 的级别",
  tierUpdated: "级别已设为 {tier}",
  stripeLinked: "已关联 Stripe 客户",
  stripeNone: "无 Stripe 客户",
  isAdmin: "管理员",
  notAdmin: "非管理员",
  grantAdmin: "授予 {email} 管理员权限",
  revokeAdmin: "撤销 {email} 的管理员权限",
  grantTitle: "授予 {email} 管理员权限？",
  grantBody: "管理员可以查看和编辑所有用户，包括级别和密码。",
  grantConfirm: "授予管理员",
  revokeTitle: "撤销 {email} 的管理员权限？",
  revokeBody: "他们保留账户和飞行记录，但无法再访问此页面。",
  revokeConfirm: "撤销管理员",
  adminGranted: "已授予管理员权限",
  adminRevoked: "已撤销管理员权限",
  resetPw: "重置密码",
  resetTitle: "重置 {email} 的密码？",
  resetBody: "当前密码会立即失效。您将获得一个新的临时密码以分享给对方。",
  resetConfirm: "生成新密码",
  resetDone: "密码已重置",
  resetDoneBody: "{email} 的新密码——请安全分享。他们应在首次登录时修改。",
  deleteUser: "删除",
  deleteArmTitle: "删除 {email}？",
  deleteArmBody: "这将清除其账户、飞行记录、文档和文件，且无法撤销。输入邮箱以继续。",
  deleteTypeLabel: "输入邮箱以确认",
  deleteContinue: "永久删除",
  deleteTitle: "永久删除 {email}？",
  deleteBody: "其登录信息、个人资料、飞行记录、文档和上传的文件都将被移除。此操作无法撤销。",
  deleteConfirm: "删除账户",
  deleted: "账户已删除",
  deletedBody: "{email} 及其全部数据已删除。",
  errNetwork: "网络错误——请重试。您的网络连接可能不稳定。",
  errUnexpected: "出了点问题，请重试。",
  errEmail: "请输入有效的邮箱地址",
};

const es: Table = {
  title: "Admin · Usuarios",
  subtitle: "Todas las cuentas, con controles de nivel y de administrador.",
  statTotal: "Usuarios",
  statFree: "Gratis",
  statPro: "Pro",
  statLifetime: "Vitalicio",
  search: "Buscar usuarios",
  searchPh: "Buscar por correo o nombre…",
  createUser: "Crear usuario",
  createTitle: "Crear nuevo usuario",
  createDesc: "La cuenta se confirma automáticamente — el usuario puede iniciar sesión de inmediato con la contraseña temporal que generamos.",
  email: "Correo",
  password: "Contraseña",
  signIn: "Iniciar sesión",
  fullName: "Nombre completo",
  tier: "Nivel",
  tierFree: "Gratis",
  tierPro: "Pro",
  tierLifetime: "Vitalicio",
  creating: "Creando…",
  created: "Cuenta creada",
  createdBody: "Comparte estas credenciales con {email} de forma segura (gestor de contraseñas o mensaje cifrado). Debe cambiar la contraseña en su primer inicio de sesión.",
  tempPassword: "Contraseña temporal",
  copyCredentials: "Copiar credenciales",
  credentialsCopied: "Credenciales copiadas",
  copyFailed: "No se pudo copiar — selecciona el texto y cópialo manualmente.",
  dismiss: "Cerrar",
  colEmail: "Correo",
  colName: "Nombre",
  colTier: "Nivel",
  colRegime: "Régimen",
  colStripe: "Stripe",
  colAdmin: "Admin",
  colSignedUp: "Alta",
  colLastSeen: "Última actividad",
  colActions: "Acciones",
  noMatch: "Ningún usuario coincide con “{q}”.",
  noUsers: "Aún no hay usuarios.",
  editName: "Editar el nombre de {email}",
  nameLabel: "Nombre",
  save: "Guardar",
  cancel: "Cancelar",
  nameSaved: "Nombre actualizado",
  tierLabel: "Nivel de {email}",
  tierUpdated: "Nivel cambiado a {tier}",
  stripeLinked: "Cliente de Stripe vinculado",
  stripeNone: "Sin cliente de Stripe",
  isAdmin: "Admin",
  notAdmin: "No es admin",
  grantAdmin: "Dar admin a {email}",
  revokeAdmin: "Quitar admin a {email}",
  grantTitle: "¿Dar permisos de admin a {email}?",
  grantBody: "Los admins pueden ver y editar a todos los usuarios, incluidos niveles y contraseñas.",
  grantConfirm: "Dar admin",
  revokeTitle: "¿Quitar admin a {email}?",
  revokeBody: "Conserva su cuenta y sus vuelos, pero pierde el acceso a esta página.",
  revokeConfirm: "Quitar admin",
  adminGranted: "Permisos de admin otorgados",
  adminRevoked: "Permisos de admin retirados",
  resetPw: "Restablecer contraseña",
  resetTitle: "¿Restablecer la contraseña de {email}?",
  resetBody: "Su contraseña actual deja de funcionar de inmediato. Obtendrás una nueva contraseña temporal para compartir.",
  resetConfirm: "Generar nueva contraseña",
  resetDone: "Contraseña restablecida",
  resetDoneBody: "Nueva contraseña para {email} — compártela de forma segura. Debe cambiarla en su primer inicio de sesión.",
  deleteUser: "Eliminar",
  deleteArmTitle: "¿Eliminar a {email}?",
  deleteArmBody: "Esto borra su cuenta, vuelos, documentos y archivos. No hay vuelta atrás. Escribe el correo para continuar.",
  deleteTypeLabel: "Escribe el correo para confirmar",
  deleteContinue: "Eliminar permanentemente",
  deleteTitle: "¿Eliminar permanentemente a {email}?",
  deleteBody: "Se eliminan su acceso, perfil, vuelos, documentos y archivos subidos. No se puede deshacer.",
  deleteConfirm: "Eliminar cuenta",
  deleted: "Cuenta eliminada",
  deletedBody: "{email} y todos sus datos han desaparecido.",
  errNetwork: "Error de red — inténtalo de nuevo. Tu conexión puede ser inestable.",
  errUnexpected: "Algo salió mal. Inténtalo de nuevo.",
  errEmail: "Ingresa un correo válido",
};

const STRINGS: Record<Locale, Table> = { en, ko, zh, es };

export type AdminT = (key: AdminStringKey, vars?: Record<string, string | number>) => string;

/** Bound translator for the admin page; falls back to English, never to the key. */
export function adminStrings(locale: Locale): AdminT {
  const table = STRINGS[locale] ?? STRINGS.en;
  return (key, vars) => {
    let str: string = table[key] ?? STRINGS.en[key];
    if (vars) {
      for (const [k, v] of Object.entries(vars)) str = str.split(`{${k}}`).join(String(v));
    }
    return str;
  };
}
