"use client";

import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import type { Airport } from "@/lib/airports";
import type { Locale } from "@/lib/i18n";
import { useReducedMotion } from "@/lib/use-reduced-motion";
import { Icon } from "@/components/ui";
// TODO(icons): fold Pause / Play into components/ui/icons.ts (owned by another
// phase); imported directly until then, same as CustomBars.tsx.
import { Pause, Play } from "lucide-react";
import { fmt, type GlobeStrings } from "./charts-strings";

/**
 * Career route globe — a night globe drawn on a 2D canvas.
 *
 * Land is ~8.7k dots (public/globe-land.bin, generated by
 * scripts/gen-globe-land.ts) on an orthographic sphere; every route flown is a
 * lifted great-circle arc, the busiest carry an aircraft and contrail, airports
 * pulse by traffic, and a cockpit-style HUD (heading tape, position, UTC)
 * frames the view. No WebGL and no 3D library: it renders anywhere a canvas
 * does, so the page can't be taken down by a missing GPU, and Charts no longer
 * ships three.js.
 *
 * Motion: slow auto-rotate that yields to any interaction and resumes after an
 * idle; route fly-to and reset ease the camera. `prefers-reduced-motion`
 * stops rotation, aircraft and pulses, and every camera move is instant.
 *
 * Input:
 *  - Mouse/pen: drag to rotate, wheel to zoom while the stage is hovered or
 *    focused (a page scroll that passes over it never zooms), hover a route or
 *    airport for its details, click a route to select it.
 *  - Coarse pointers start parked (`touch-action: pan-y`, touches ignored) so a
 *    swipe scrolls the page; "Tap to explore" arms one-finger rotate and
 *    two-finger pinch; "Done" parks it again.
 *  - The stage is focusable; arrow keys nudge the view (Shift = coarse).
 */

interface ArcDatum {
  id: string; from: string; to: string;
  startLat: number; startLng: number; endLat: number; endLng: number;
  count: number; km: number;
}
interface PointDatum {
  code: string; name: string; country: string;
  lat: number; lng: number; traffic: number; hub: boolean;
}

export interface GlobeProps {
  airports: Record<string, Airport>;
  arcs: Array<{ from: string; to: string; count: number }>;
  strings: GlobeStrings;
  locale: Locale;
  /** Kept for WebGLGate compatibility; a 2D canvas never loses a GPU context. */
  onUnavailable?: () => void;
  /** Shade the night side from the real sun position (default on). */
  nightShade?: boolean;
  /** Legs a visitor typed (marketing page): drawn on top, camera fits them. */
  visitorLegs?: Array<{ from: string; to: string }>;
  /** Show the route chip strip under the globe on phones (app only; off on the dark marketing page). */
  chipStrip?: boolean;
  /** Show the top-routes panel over the stage on md+ (off where the stage is too narrow to share). */
  routesPanel?: boolean;
}

// ---------- palette (CSS custom properties, "r g b" triples) ----------
const TOKENS = {
  night1: "--globe-night-1", night2: "--globe-night-2", night3: "--globe-night-3",
  glow: "--globe-glow", dots: "--globe-dots", route: "--globe-route", trail: "--globe-trail",
  plane: "--globe-plane", sel: "--globe-arc-sel-to", hub: "--globe-hub", ink: "--globe-ink",
} as const;
type Palette = Record<keyof typeof TOKENS, string>;
function readPalette(): Palette {
  const css = typeof document === "undefined" ? null : getComputedStyle(document.documentElement);
  const out = {} as Palette;
  for (const [k, v] of Object.entries(TOKENS)) out[k as keyof Palette] = (css?.getPropertyValue(v).trim() || "255 255 255").split(/\s+/).join(",");
  return out;
}
const rgba = (triple: string, a: number) => `rgba(${triple},${a.toFixed(3)})`;

// ---------- spherical helpers ----------
const R_EARTH_KM = 6371;
const D2R = Math.PI / 180;
type V3 = [number, number, number];
function toVec(lat: number, lng: number): V3 {
  const la = lat * D2R, lo = lng * D2R;
  return [Math.cos(la) * Math.cos(lo), Math.cos(la) * Math.sin(lo), Math.sin(la)];
}
function fromVec([x, y, z]: V3) {
  const n = Math.hypot(x, y, z) || 1;
  return { lat: Math.asin(z / n) / D2R, lng: Math.atan2(y, x) / D2R };
}
function angularDistance(aLat: number, aLng: number, bLat: number, bLng: number) {
  const [ax, ay, az] = toVec(aLat, aLng);
  const [bx, by, bz] = toVec(bLat, bLng);
  return Math.acos(Math.max(-1, Math.min(1, ax * bx + ay * by + az * bz)));
}
/** Deterministic 0..1 from a string — staggers aircraft without Math.random. */
function hash01(s: string) {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
  return ((h >>> 0) % 1000) / 1000;
}
const wrapDeg = (d: number) => ((((d + 180) % 360) + 360) % 360) - 180;

const ARC_SAMPLES = 48;
const MAX_PLANES = 20;
const ROTATE_DEG_PER_S = 1.6;
const ZOOM_MIN = 0.8, ZOOM_MAX = 2.4;
/** Keyboard nudge per arrow press, in degrees (Shift = coarse step). */
const NUDGE_DEG = 6;
const NUDGE_DEG_FAST = 20;

interface View { lat: number; lng: number; zoom: number }

export default function FlightGlobe({ airports, arcs: rawArcs, strings, locale, nightShade = true, visitorLegs, chipStrip = true, routesPanel = true }: GlobeProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const tipRef = useRef<HTMLDivElement>(null);
  const hintId = useId();
  const reduceMotion = useReducedMotion();
  const [stageH, setStageH] = useState(560);
  const [landReady, setLandReady] = useState(false);
  const [rotateOn, setRotateOn] = useState(true);
  const [selected, setSelected] = useState<string | null>(null);
  const [tip, setTip] = useState<string | null>(null);
  /** Primary pointer is touch — the stage stays parked until the user arms it. */
  const [coarse, setCoarse] = useState(false);
  const [armed, setArmed] = useState(false);

  const flightCount = useCallback(
    (n: number) => fmt(n === 1 ? strings.flightOne : strings.flightMany, { n: n.toLocaleString(locale) }),
    [strings, locale],
  );

  // ---------- data ----------
  const arcs = useMemo<ArcDatum[]>(() => {
    const out: ArcDatum[] = [];
    for (const { from, to, count } of rawArcs) {
      const a = airports[from], b = airports[to];
      if (!a || !b) continue;
      out.push({
        id: `${from}-${to}`, from, to,
        startLat: a.lat, startLng: a.lon, endLat: b.lat, endLng: b.lon,
        count, km: Math.round(angularDistance(a.lat, a.lon, b.lat, b.lon) * R_EARTH_KM),
      });
    }
    return out.sort((x, y) => y.count - x.count);
  }, [airports, rawArcs]);
  const maxCount = useMemo(() => arcs.reduce((m, a) => Math.max(m, a.count), 1), [arcs]);

  const points = useMemo<PointDatum[]>(() => {
    const traffic = new Map<string, number>();
    for (const a of arcs) {
      traffic.set(a.from, (traffic.get(a.from) ?? 0) + a.count);
      traffic.set(a.to, (traffic.get(a.to) ?? 0) + a.count);
    }
    const list: PointDatum[] = Object.entries(airports).map(([code, a]) => ({
      code, name: a.name, country: a.country, lat: a.lat, lng: a.lon,
      traffic: traffic.get(code) ?? 0, hub: false,
    }));
    list.sort((x, y) => y.traffic - x.traffic);
    const hubCut = Math.max(1, Math.ceil(list.length * 0.1));
    list.forEach((p, i) => { p.hub = i < hubCut && p.traffic > 0; });
    return list;
  }, [airports, arcs]);
  const topRoutes = useMemo(() => arcs.slice(0, 6), [arcs]);

  // Traffic-weighted spherical mean of the airports: a "home" view that
  // handles the antimeridian (a plain average of YVR + HKG lands in Kansas).
  const home = useMemo<View>(() => {
    let x = 0, y = 0, z = 0;
    for (const p of points) {
      const w = Math.sqrt(p.traffic) + 0.2;
      const [a, b, c] = toVec(p.lat, p.lng);
      x += a * w; y += b * w; z += c * w;
    }
    const c = (!x && !y && !z) ? { lat: 30, lng: -40 } : fromVec([x, y, z]);
    return { lat: Math.max(-60, Math.min(60, c.lat)), lng: c.lng, zoom: 1 };
  }, [points]);

  // Geometry handed to the render loop (rebuilt only when the data changes).
  const scene = useMemo(() => {
    const maxTraffic = points.reduce((m, p) => Math.max(m, p.traffic), 1);
    const routes = arcs.map((a, i) => {
      const A = toVec(a.startLat, a.startLng), B = toVec(a.endLat, a.endLng);
      const w = Math.acos(Math.max(-1, Math.min(1, A[0] * B[0] + A[1] * B[1] + A[2] * B[2])));
      const sw = Math.sin(w) || 1e-6;
      const lift = 0.02 + 0.16 * (w / Math.PI);
      const pts = new Float32Array((ARC_SAMPLES + 1) * 3);
      for (let k = 0; k <= ARC_SAMPLES; k++) {
        const t = k / ARC_SAMPLES;
        const f1 = w < 1e-6 ? 1 - t : Math.sin((1 - t) * w) / sw, f2 = w < 1e-6 ? t : Math.sin(t * w) / sw;
        const r = 1 + lift * Math.sin(Math.PI * t);
        pts[3 * k] = (f1 * A[0] + f2 * B[0]) * r;
        pts[3 * k + 1] = (f1 * A[1] + f2 * B[1]) * r;
        pts[3 * k + 2] = (f1 * A[2] + f2 * B[2]) * r;
      }
      return { arc: a, pts, weight: Math.pow(a.count / maxCount, 0.6), plane: i < MAX_PLANES, phase: hash01(a.id), speed: 0.06 / (0.25 + w) };
    });
    const dots = points.filter((p) => p.traffic > 0).map((p, i) => ({ p, v: toVec(p.lat, p.lng), r: 1.6 + 3.2 * Math.sqrt(p.traffic / maxTraffic), label: i < 12, ring: i < 3, ph: hash01(p.code) }));
    return { routes, dots };
  }, [arcs, points, maxCount]);

  // Visitor-typed legs: their own arcs, aircraft and labels, drawn over the sample.
  const visitor = useMemo(() => {
    const legs: { arc: ArcDatum; pts: Float32Array }[] = [];
    const codes = new Map<string, V3>();
    let km = 0;
    for (const { from, to } of visitorLegs ?? []) {
      const a = airports[from], b = airports[to];
      if (!a || !b || from === to) continue;
      const A = toVec(a.lat, a.lon), B = toVec(b.lat, b.lon);
      const w = Math.acos(Math.max(-1, Math.min(1, A[0] * B[0] + A[1] * B[1] + A[2] * B[2])));
      const sw = Math.sin(w) || 1e-6, lift = 0.03 + 0.18 * (w / Math.PI);
      const pts = new Float32Array((ARC_SAMPLES + 1) * 3);
      for (let k = 0; k <= ARC_SAMPLES; k++) {
        const t = k / ARC_SAMPLES, f1 = Math.sin((1 - t) * w) / sw, f2 = Math.sin(t * w) / sw, r = 1 + lift * Math.sin(Math.PI * t);
        pts[3 * k] = (f1 * A[0] + f2 * B[0]) * r; pts[3 * k + 1] = (f1 * A[1] + f2 * B[1]) * r; pts[3 * k + 2] = (f1 * A[2] + f2 * B[2]) * r;
      }
      const d = Math.round(w * R_EARTH_KM); km += d;
      legs.push({ arc: { id: `v:${from}-${to}`, from, to, startLat: a.lat, startLng: a.lon, endLat: b.lat, endLng: b.lon, count: 1, km: d }, pts });
      codes.set(from, A); codes.set(to, B);
    }
    return { legs, codes: [...codes.entries()], km };
  }, [visitorLegs, airports]);

  // ---------- live refs read by the render loop ----------
  const view = useRef<View>({ ...home });
  const anim = useRef<{ from: View; to: View; t0: number; dur: number } | null>(null);
  const ui = useRef({ rotateOn: true, selected: null as string | null, reduceMotion: false, coarse: false, armed: false, zoomHot: false, resumeAt: 0 });
  const sceneRef = useRef(scene);
  const visitorRef = useRef(visitor);
  const nightRef = useRef(nightShade);
  useEffect(() => { nightRef.current = nightShade; kick.current(); }, [nightShade]);
  const kick = useRef<() => void>(() => {});
  const hoverArc = useRef<ArcDatum | null>(null);
  useEffect(() => { sceneRef.current = scene; kick.current(); }, [scene]);
  useEffect(() => { visitorRef.current = visitor; kick.current(); }, [visitor]);
  useEffect(() => { ui.current.rotateOn = rotateOn; kick.current(); }, [rotateOn]);
  useEffect(() => { ui.current.selected = selected; kick.current(); }, [selected]);
  useEffect(() => { ui.current.reduceMotion = reduceMotion; if (reduceMotion) setRotateOn(false); kick.current(); }, [reduceMotion]);
  useEffect(() => { ui.current.coarse = coarse; ui.current.armed = armed; }, [coarse, armed]);

  useEffect(() => {
    const mq = window.matchMedia?.("(pointer: coarse)");
    if (!mq) return;
    const update = () => setCoarse(mq.matches);
    update();
    mq.addEventListener?.("change", update);
    return () => mq.removeEventListener?.("change", update);
  }, []);

  // ---------- camera actions ----------
  const moveTo = useCallback((to: View, dur: number) => {
    const instant = ui.current.reduceMotion || dur <= 0;
    if (instant) { view.current = { ...to }; anim.current = null; }
    else anim.current = { from: { ...view.current }, to, t0: performance.now(), dur };
    kick.current();
  }, []);
  const holdRotation = useCallback((ms: number) => { ui.current.resumeAt = performance.now() + ms; }, []);

  const flyTo = useCallback((a: ArcDatum) => {
    const [x1, y1, z1] = toVec(a.startLat, a.startLng);
    const [x2, y2, z2] = toVec(a.endLat, a.endLng);
    const mid = fromVec([x1 + x2, y1 + y2, z1 + z2]);
    const theta = angularDistance(a.startLat, a.startLng, a.endLat, a.endLng);
    const zoom = Math.max(ZOOM_MIN, Math.min(1.9, 1.35 / Math.max(0.42, 0.3 + theta * 1.2)));
    holdRotation(8000);
    moveTo({ lat: mid.lat, lng: mid.lng, zoom }, 1100);
  }, [holdRotation, moveTo]);

  const selectRoute = useCallback((a: ArcDatum | null) => {
    setSelected((prev) => (a && prev === a.id ? null : a?.id ?? null));
    if (a) flyTo(a);
  }, [flyTo]);

  const resetView = useCallback(() => {
    setSelected(null);
    holdRotation(2000);
    moveTo({ ...home }, 1100);
  }, [home, holdRotation, moveTo]);

  const nudge = useCallback((dLat: number, dLng: number) => {
    const v = anim.current?.to ?? view.current;
    holdRotation(4000);
    moveTo({ lat: Math.max(-85, Math.min(85, v.lat + dLat)), lng: wrapDeg(v.lng + dLng), zoom: v.zoom }, 240);
  }, [holdRotation, moveTo]);

  // A visitor drew routes: clear any selection and fit the camera to them.
  useEffect(() => {
    if (!visitor.codes.length) return;
    let x = 0, y = 0, z = 0;
    for (const [, v] of visitor.codes) { x += v[0]; y += v[1]; z += v[2]; }
    const c = fromVec([x, y, z]);
    const [cxv, cyv, czv] = toVec(c.lat, c.lng);
    let spread = 0;
    for (const [, v] of visitor.codes) spread = Math.max(spread, Math.acos(Math.max(-1, Math.min(1, v[0] * cxv + v[1] * cyv + v[2] * czv))));
    setSelected(null);
    holdRotation(12000);
    moveTo({ lat: Math.max(-70, Math.min(70, c.lat)), lng: c.lng, zoom: Math.max(ZOOM_MIN, Math.min(1.9, 1.25 / Math.max(0.5, 0.35 + spread * 1.1))) }, 1100);
  }, [visitor, holdRotation, moveTo]);

  const onKeyDown = useCallback((e: React.KeyboardEvent<HTMLDivElement>) => {
    const step = e.shiftKey ? NUDGE_DEG_FAST : NUDGE_DEG;
    switch (e.key) {
      case "ArrowLeft":  e.preventDefault(); nudge(0, -step); break;
      case "ArrowRight": e.preventDefault(); nudge(0, step); break;
      case "ArrowUp":    e.preventDefault(); nudge(step, 0); break;
      case "ArrowDown":  e.preventDefault(); nudge(-step, 0); break;
      default: break;
    }
  }, [nudge]);

  // ---------- render loop + input (one effect for the canvas' lifetime) ----------
  const tipTextFor = useRef<(kind: "arc" | "dot", d: ArcDatum | PointDatum) => string>(() => "");
  tipTextFor.current = (kind, d) => {
    if (kind === "arc") {
      const a = d as ArcDatum;
      const km = fmt(strings.km, { n: a.km.toLocaleString(locale) });
      return a.id.startsWith("v:") ? `${a.from} → ${a.to} · ${km}` : `${a.from} → ${a.to} · ${flightCount(a.count)} · ${km}`;
    }
    const p = d as PointDatum;
    return `${p.code} — ${p.name}${p.country ? `, ${p.country}` : ""} · ${flightCount(p.traffic)}`;
  };
  const selectRef = useRef(selectRoute);
  selectRef.current = selectRoute;

  useEffect(() => {
    const canvas = canvasRef.current;
    const ctx = canvas?.getContext("2d");
    if (!canvas || !ctx) return;
    const pal = readPalette();
    let land: Float32Array | null = null;
    let raf = 0, last = performance.now(), visible = true, t = 0, W = 0, H = 0, dpr = 1;
    let cancelled = false;

    fetch("/globe-land.bin")
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(String(r.status)))))
      .then((buf) => {
        if (cancelled) return;
        const raw = new Int16Array(buf);
        const out = new Float32Array((raw.length / 2) * 3);
        for (let i = 0; i < raw.length / 2; i++) {
          const v = toVec(raw[2 * i] / 10, raw[2 * i + 1] / 10);
          out[3 * i] = v[0]; out[3 * i + 1] = v[1]; out[3 * i + 2] = v[2];
        }
        land = out;
        setLandReady(true);
        kickNow();
      })
      .catch(() => { if (!cancelled) { setLandReady(true); kickNow(); } }); // routes still draw on a plain sphere

    // projection scratch
    const o = [0, 0, 0, 0, 0];
    let cl = 1, sl = 0, cp = 1, sp = 0, R = 1, cx = 0, cy = 0;
    const P = (x: number, y: number, z: number) => {
      const x1 = x * cl + y * sl, y1 = -x * sl + y * cl, z2 = -x1 * sp + z * cp;
      o[0] = x1 * cp + z * sp; o[1] = cx + R * y1; o[2] = cy - R * z2; o[3] = y1; o[4] = z2;
    };
    const vis = () => o[0] > 0 || o[3] * o[3] + o[4] * o[4] > 1.0004;
    const DOT_A = [0.18, 0.34, 0.52, 0.72, 0.94];
    const DOT_S = [1.0, 1.25, 1.5, 1.8, 2.1];
    // 5 depth bands × 3 light states (day, twilight, night)
    const bx: number[][] = Array.from({ length: 15 }, () => []), by: number[][] = Array.from({ length: 15 }, () => []);
    /** Subsolar point → unit vector (declination + hour angle; equation of time ignored, ±4°). */
    const sunVec = (): V3 => {
      const now = new Date();
      const start = Date.UTC(now.getUTCFullYear(), 0, 0);
      const day = (now.getTime() - start) / 86400000;
      const decl = -23.44 * Math.cos(((2 * Math.PI) / 365) * (day + 10));
      const h = now.getUTCHours() + now.getUTCMinutes() / 60 + now.getUTCSeconds() / 3600;
      return toVec(decl, wrapDeg(-15 * (h - 12)));
    };
    /** Screen-space samples of the visible arcs, kept for hover hit-testing. */
    let hitArcs: { arc: ArcDatum; xy: Float32Array; n: number }[] = [];
    let hitDots: { p: PointDatum; x: number; y: number }[] = [];

    const draw = () => {
      const { routes, dots } = sceneRef.current;
      const sel = ui.current.selected;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, W, H);
      const v = view.current;
      const base = Math.min(W, H) * 0.4;
      R = base * v.zoom; cx = W / 2; cy = H / 2 + 8;
      const lam = v.lng * D2R, phi = v.lat * D2R;
      cl = Math.cos(lam); sl = Math.sin(lam); cp = Math.cos(phi); sp = Math.sin(phi);

      let g = ctx.createRadialGradient(cx, cy, R * 0.94, cx, cy, R * 1.24);
      g.addColorStop(0, rgba(pal.glow, 0.24)); g.addColorStop(0.35, rgba(pal.glow, 0.08)); g.addColorStop(1, rgba(pal.glow, 0));
      ctx.fillStyle = g; ctx.beginPath(); ctx.arc(cx, cy, R * 1.24, 0, Math.PI * 2); ctx.fill();
      g = ctx.createRadialGradient(cx - R * 0.38, cy - R * 0.42, R * 0.05, cx, cy, R);
      g.addColorStop(0, `rgb(${pal.night1})`); g.addColorStop(0.5, `rgb(${pal.night2})`); g.addColorStop(1, `rgb(${pal.night3})`);
      ctx.fillStyle = g; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fill();

      // night side of the ocean: a soft band across the terminator, along the
      // projected sun direction (exact on that axis, soft enough elsewhere)
      const night = nightRef.current;
      const S3 = night ? sunVec() : ([0, 0, 0] as V3);
      if (night) {
        P(S3[0], S3[1], S3[2]);
        const sx = o[0], spx = o[3], spy = -o[4], sp = Math.hypot(spx, spy);
        if (sp > 0.01) {
          const dx = spx / sp, dy = spy / sp, f = Math.max(0, Math.min(1, (1 - sx) / 2));
          const gn = ctx.createLinearGradient(cx - dx * R, cy - dy * R, cx + dx * R, cy + dy * R);
          gn.addColorStop(0, "rgba(2,6,14,0.4)"); gn.addColorStop(Math.max(0, f - 0.07), "rgba(2,6,14,0.4)");
          gn.addColorStop(Math.min(1, f + 0.07), "rgba(2,6,14,0)"); gn.addColorStop(1, "rgba(2,6,14,0)");
          ctx.fillStyle = gn; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fill();
        } else if (sx < 0) {
          ctx.fillStyle = "rgba(2,6,14,0.4)"; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.fill();
        }
      }

      if (land) {
        for (let b = 0; b < 15; b++) { bx[b].length = 0; by[b].length = 0; }
        const n = land.length / 3;
        for (let i = 0; i < n; i++) {
          const lx = land[3 * i], ly = land[3 * i + 1], lz = land[3 * i + 2];
          P(lx, ly, lz);
          if (o[0] <= 0.03 || o[1] < -4 || o[1] > W + 4 || o[2] < -4 || o[2] > H + 4) continue;
          const light = night ? lx * S3[0] + ly * S3[1] + lz * S3[2] : 1;
          const state = light > 0.06 ? 0 : light > -0.06 ? 1 : 2;
          const b = Math.min(4, (o[0] * 5) | 0) + 5 * state; bx[b].push(o[1]); by[b].push(o[2]);
        }
        const zs = Math.min(1.6, Math.max(1, v.zoom * 0.75));
        for (let b = 0; b < 15; b++) {
          const d = b % 5, state = (b / 5) | 0;
          // day: cyan land · twilight: dimmer · night: faint warm "city lights"
          ctx.fillStyle = state === 0 ? rgba(pal.dots, DOT_A[d]) : state === 1 ? rgba(pal.dots, DOT_A[d] * 0.7) : rgba(pal.trail, DOT_A[d] * 0.55);
          const z = DOT_S[d] * zs, hz = z / 2, X = bx[b], Y = by[b];
          for (let j = 0; j < X.length; j++) ctx.fillRect(X[j] - hz, Y[j] - hz, z, z);
        }
      }
      ctx.strokeStyle = rgba(pal.glow, 0.38); ctx.lineWidth = 1.2; ctx.beginPath(); ctx.arc(cx, cy, R, 0, Math.PI * 2); ctx.stroke();

      // routes
      hitArcs = [];
      ctx.lineCap = "round";
      for (const r of routes) {
        const isSel = sel === r.arc.id, dim = !!sel && !isSel;
        const xy = new Float32Array((ARC_SAMPLES + 1) * 2);
        let n = 0;
        ctx.beginPath(); let pen = false;
        for (let k = 0; k <= ARC_SAMPLES; k++) {
          P(r.pts[3 * k], r.pts[3 * k + 1], r.pts[3 * k + 2]);
          if (vis()) { if (pen) ctx.lineTo(o[1], o[2]); else ctx.moveTo(o[1], o[2]); pen = true; xy[2 * n] = o[1]; xy[2 * n + 1] = o[2]; n++; }
          else { pen = false; if (n) { xy[2 * n] = NaN; xy[2 * n + 1] = NaN; n++; } }
        }
        ctx.lineWidth = isSel ? 2.6 : 0.8 + 1.6 * r.weight;
        ctx.strokeStyle = isSel ? rgba(pal.sel, 0.95) : rgba(pal.route, dim ? 0.07 : 0.18 + 0.5 * r.weight);
        ctx.stroke();
        if (n > 1) hitArcs.push({ arc: r.arc, xy, n });

        if (!(r.plane || isSel) || dim) continue;
        const N = ARC_SAMPLES;
        const p = ui.current.reduceMotion ? 0.55 : (r.phase + t * r.speed) % 1;
        const head = p * N, L = N * 0.18, from = head - L;
        ctx.lineWidth = isSel ? 2.4 : 1.6;
        let px = 0, py = 0, pv = false;
        for (let s = 0; s <= 10; s++) {
          const f = from + (head - from) * (s / 10);
          if (f < 0) { pv = false; continue; }
          const k = Math.min(N - 1, Math.floor(f)), u = f - k;
          P(r.pts[3 * k] + (r.pts[3 * k + 3] - r.pts[3 * k]) * u, r.pts[3 * k + 1] + (r.pts[3 * k + 4] - r.pts[3 * k + 1]) * u, r.pts[3 * k + 2] + (r.pts[3 * k + 5] - r.pts[3 * k + 2]) * u);
          const vv = vis();
          if (pv && vv) { ctx.strokeStyle = rgba(pal.trail, 0.85 * (s / 10)); ctx.beginPath(); ctx.moveTo(px, py); ctx.lineTo(o[1], o[2]); ctx.stroke(); }
          px = o[1]; py = o[2]; pv = vv;
        }
        const k = Math.min(N - 1, Math.floor(head)), u = head - k;
        P(r.pts[3 * k] + (r.pts[3 * k + 3] - r.pts[3 * k]) * u, r.pts[3 * k + 1] + (r.pts[3 * k + 4] - r.pts[3 * k + 1]) * u, r.pts[3 * k + 2] + (r.pts[3 * k + 5] - r.pts[3 * k + 2]) * u);
        if (!vis()) continue;
        const hx = o[1], hy = o[2], depth = o[0];
        P(r.pts[3 * (k + 1)], r.pts[3 * (k + 1) + 1], r.pts[3 * (k + 1) + 2]);
        const ang = Math.atan2(o[2] - hy, o[1] - hx), sz = 3.2 + 1.4 * Math.max(0, depth);
        ctx.fillStyle = rgba(pal.trail, 0.16); ctx.beginPath(); ctx.arc(hx, hy, sz * 2.1, 0, Math.PI * 2); ctx.fill();
        ctx.save(); ctx.translate(hx, hy); ctx.rotate(ang); ctx.fillStyle = `rgb(${pal.plane})`;
        ctx.beginPath(); ctx.moveTo(sz * 1.5, 0); ctx.lineTo(-sz, sz * 0.95); ctx.lineTo(-sz * 0.45, 0); ctx.lineTo(-sz, -sz * 0.95); ctx.closePath(); ctx.fill();
        ctx.restore();
      }

      // visitor legs: bright, always flying, labelled
      const vis2 = visitorRef.current;
      for (const leg of vis2.legs) {
        const pts = leg.pts, N = ARC_SAMPLES;
        const xy = new Float32Array((N + 1) * 2);
        let n = 0, pen = false;
        ctx.beginPath();
        for (let k = 0; k <= N; k++) {
          P(pts[3 * k], pts[3 * k + 1], pts[3 * k + 2]);
          if (vis()) { if (pen) ctx.lineTo(o[1], o[2]); else ctx.moveTo(o[1], o[2]); pen = true; xy[2 * n] = o[1]; xy[2 * n + 1] = o[2]; n++; }
          else { pen = false; if (n) { xy[2 * n] = NaN; xy[2 * n + 1] = NaN; n++; } }
        }
        ctx.lineWidth = 2.4; ctx.strokeStyle = rgba(pal.sel, 0.95); ctx.stroke();
        if (n > 1) hitArcs.push({ arc: leg.arc, xy, n });
        const p = ui.current.reduceMotion ? 0.6 : (hash01(leg.arc.id) + t * 0.12) % 1;
        const head = p * N, k = Math.min(N - 1, Math.floor(head)), u = head - k;
        P(pts[3 * k] + (pts[3 * k + 3] - pts[3 * k]) * u, pts[3 * k + 1] + (pts[3 * k + 4] - pts[3 * k + 1]) * u, pts[3 * k + 2] + (pts[3 * k + 5] - pts[3 * k + 2]) * u);
        if (!vis()) continue;
        const hx = o[1], hy = o[2];
        P(pts[3 * (k + 1)], pts[3 * (k + 1) + 1], pts[3 * (k + 1) + 2]);
        const ang = Math.atan2(o[2] - hy, o[1] - hx), sz = 4.6;
        ctx.fillStyle = rgba(pal.sel, 0.22); ctx.beginPath(); ctx.arc(hx, hy, sz * 2.3, 0, Math.PI * 2); ctx.fill();
        ctx.save(); ctx.translate(hx, hy); ctx.rotate(ang); ctx.fillStyle = `rgb(${pal.plane})`;
        ctx.beginPath(); ctx.moveTo(sz * 1.5, 0); ctx.lineTo(-sz, sz * 0.95); ctx.lineTo(-sz * 0.45, 0); ctx.lineTo(-sz, -sz * 0.95); ctx.closePath(); ctx.fill();
        ctx.restore();
      }
      // Labels never overlap: visitor airports claim their spot first, then the busiest sample airports.
      const placed: number[] = [];
      const claim = (x: number, y: number, w: number) => {
        for (let i = 0; i < placed.length; i += 4) if (x < placed[i + 2] && x + w > placed[i] && y - 11 < placed[i + 3] && y + 2 > placed[i + 1]) return false;
        placed.push(x, y - 11, x + w, y + 2); return true;
      };
      ctx.font = '700 11px "JetBrains Mono", ui-monospace, monospace';
      for (const [code, cv] of vis2.codes) {
        P(cv[0], cv[1], cv[2]);
        if (o[0] <= 0.02) continue;
        ctx.fillStyle = rgba(pal.sel, 1); ctx.beginPath(); ctx.arc(o[1], o[2], 3.4, 0, Math.PI * 2); ctx.fill();
        if (claim(o[1] + 7, o[2] - 7, 32)) { ctx.fillStyle = rgba(pal.ink, 0.95); ctx.fillText(code, o[1] + 7, o[2] - 7); }
      }

      // airports
      hitDots = [];
      ctx.font = '600 10px "JetBrains Mono", ui-monospace, monospace';
      ctx.textAlign = "left";
      for (const d of dots) {
        P(d.v[0], d.v[1], d.v[2]);
        if (o[0] <= 0.04) continue;
        const a = Math.min(1, o[0] * 1.4);
        if (d.ring && !ui.current.reduceMotion) {
          const ring = (t * 0.45 + d.ph) % 1;
          ctx.strokeStyle = rgba(pal.hub, (1 - ring) * 0.55 * a); ctx.lineWidth = 1;
          ctx.beginPath(); ctx.arc(o[1], o[2], d.r + ring * 10, 0, Math.PI * 2); ctx.stroke();
        }
        ctx.fillStyle = d.p.hub ? rgba(pal.hub, 0.95 * a) : rgba(pal.ink, 0.9 * a);
        ctx.beginPath(); ctx.arc(o[1], o[2], d.r * Math.min(1.6, Math.max(0.8, v.zoom * 0.7)), 0, Math.PI * 2); ctx.fill();
        if (d.label && o[0] > 0.35 && Math.min(W, H) > 340 && claim(o[1] + 6, o[2] - 6, 30)) { ctx.fillStyle = rgba(pal.ink, 0.78 * a); ctx.fillText(d.p.code, o[1] + 6, o[2] - 6); }
        hitDots.push({ p: d.p, x: o[1], y: o[2] });
      }

      // HUD: heading tape (top centre), position + UTC (bottom centre)
      const hdg = (((-v.lng) % 360) + 360) % 360;
      const TW = Math.min(W * 0.4, 300), ppd = TW / 70, ty = 22;
      ctx.lineWidth = 1; ctx.textAlign = "center";
      for (let d = Math.ceil((hdg - 35) / 5) * 5; d <= hdg + 35; d += 5) {
        const x = cx + (d - hdg) * ppd, f = Math.max(0, 1 - Math.abs(x - cx) / (TW / 2));
        const dd = ((d % 360) + 360) % 360;
        ctx.strokeStyle = rgba(pal.glow, 0.7 * f);
        ctx.beginPath(); ctx.moveTo(x, ty); ctx.lineTo(x, ty + (dd % 10 === 0 ? 8 : 4)); ctx.stroke();
        if (dd % 30 === 0) {
          const lab = dd === 0 ? "N" : dd === 90 ? "E" : dd === 180 ? "S" : dd === 270 ? "W" : String(dd / 10).padStart(2, "0");
          ctx.fillStyle = rgba(pal.ink, 0.62 * f); ctx.fillText(lab, x, ty + 20);
        }
      }
      ctx.fillStyle = rgba(pal.trail, 0.95);
      ctx.beginPath(); ctx.moveTo(cx - 4, ty - 5); ctx.lineTo(cx + 4, ty - 5); ctx.lineTo(cx, ty); ctx.closePath(); ctx.fill();
      ctx.fillText(String(Math.round(hdg) % 360).padStart(3, "0") + "°", cx, ty - 9);
      if (W >= 980) {
        const dm = (x: number) => { const a = Math.abs(x), d = Math.floor(a), m = Math.floor((a - d) * 60); return `${d}°${String(m).padStart(2, "0")}′`; };
        ctx.fillStyle = rgba(pal.ink, 0.55);
        ctx.fillText(`${v.lat >= 0 ? "N" : "S"} ${dm(v.lat)}  ${v.lng >= 0 ? "E" : "W"} ${dm(v.lng)}  ·  UTC ${new Date().toISOString().slice(11, 19)}Z`, cx, H - 12);
      }
      ctx.textAlign = "left";
    };

    const frame = (now: number) => {
      raf = 0;
      const dt = Math.min(0.05, (now - last) / 1000); last = now;
      const u = ui.current;
      const moving = !u.reduceMotion && u.rotateOn;
      if (!u.reduceMotion) t += dt;
      if (anim.current) {
        const a = anim.current, k = Math.min(1, (now - a.t0) / a.dur), e = 1 - Math.pow(1 - k, 3);
        let dl = a.to.lng - a.from.lng; if (dl > 180) dl -= 360; if (dl < -180) dl += 360;
        view.current = { lat: a.from.lat + (a.to.lat - a.from.lat) * e, lng: wrapDeg(a.from.lng + dl * e), zoom: a.from.zoom + (a.to.zoom - a.from.zoom) * e };
        if (k >= 1) anim.current = null;
      } else if (moving && !dragging && now > u.resumeAt) {
        view.current.lng = wrapDeg(view.current.lng - ROTATE_DEG_PER_S * dt);
      }
      draw();
      // keep animating while anything moves; otherwise idle until the next kick
      const busy = !u.reduceMotion || anim.current !== null || dragging;
      if (visible && busy) raf = requestAnimationFrame(frame);
    };
    const kickNow = () => { if (!raf && visible) { last = performance.now(); raf = requestAnimationFrame(frame); } };
    kick.current = kickNow;

    const resize = () => {
      const r = canvas.getBoundingClientRect();
      dpr = Math.min(2, window.devicePixelRatio || 1); W = r.width; H = r.height;
      canvas.width = Math.max(1, Math.round(W * dpr)); canvas.height = Math.max(1, Math.round(H * dpr));
      setStageH(Math.min(640, Math.max(420, Math.round(W * 0.6))));
      kickNow();
    };

    // ---------- pointer input ----------
    const pointers = new Map<number, { x: number; y: number }>();
    let dragging = false, moved = 0, pinch0 = 0, zoom0 = 1;
    const live = (e: PointerEvent) => e.pointerType !== "touch" || !ui.current.coarse || ui.current.armed;
    const hitTest = (x: number, y: number) => {
      let best: { kind: "arc" | "dot"; d: ArcDatum | PointDatum; dist: number } | null = null;
      for (const h of hitDots) { const dd = Math.hypot(h.x - x, h.y - y); if (dd < 9 && (!best || dd < best.dist)) best = { kind: "dot", d: h.p, dist: dd }; }
      if (best) return best;
      for (const h of hitArcs) {
        for (let i = 0; i + 1 < h.n; i++) {
          const ax = h.xy[2 * i], ay = h.xy[2 * i + 1], bx2 = h.xy[2 * i + 2], by2 = h.xy[2 * i + 3];
          if (Number.isNaN(ax) || Number.isNaN(bx2)) continue;
          const vx = bx2 - ax, vy = by2 - ay, l2 = vx * vx + vy * vy || 1;
          const k = Math.max(0, Math.min(1, ((x - ax) * vx + (y - ay) * vy) / l2));
          const dd = Math.hypot(ax + vx * k - x, ay + vy * k - y);
          if (dd < 6 && (!best || dd < best.dist)) best = { kind: "arc", d: h.arc, dist: dd };
        }
      }
      return best;
    };
    const local = (e: PointerEvent) => { const r = canvas.getBoundingClientRect(); return { x: e.clientX - r.left, y: e.clientY - r.top }; };
    const showTip = (hit: ReturnType<typeof hitTest>, x: number, y: number) => {
      hoverArc.current = hit?.kind === "arc" ? (hit.d as ArcDatum) : null;
      const text = hit ? tipTextFor.current(hit.kind, hit.d) : null;
      setTip(text);
      canvas.style.cursor = dragging ? "grabbing" : hit ? "pointer" : "grab";
      const el = tipRef.current;
      if (el && text) { el.style.left = `${Math.min(W - 12, x + 14)}px`; el.style.top = `${y + 14}px`; }
      if (hit) holdRotation(1500);
    };
    const down = (e: PointerEvent) => {
      if (!live(e)) return;
      pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
      try { canvas.setPointerCapture(e.pointerId); } catch { /* ignore */ }
      dragging = true; moved = 0;
      if (pointers.size === 2) { const [a, b] = [...pointers.values()]; pinch0 = Math.hypot(a.x - b.x, a.y - b.y); zoom0 = view.current.zoom; }
      anim.current = null; holdRotation(3500); kickNow();
    };
    const move = (e: PointerEvent) => {
      if (!dragging) {
        if (e.pointerType === "mouse") { const { x, y } = local(e); showTip(hitTest(x, y), x, y); }
        return;
      }
      const prev = pointers.get(e.pointerId);
      if (!prev) return;
      pointers.set(e.pointerId, { x: e.clientX, y: e.clientY });
      if (pointers.size === 2) {
        const [a, b] = [...pointers.values()];
        const d = Math.hypot(a.x - b.x, a.y - b.y);
        if (pinch0 > 0) view.current.zoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, zoom0 * (d / pinch0)));
      } else {
        const dx = e.clientX - prev.x, dy = e.clientY - prev.y;
        moved += Math.abs(dx) + Math.abs(dy);
        const k = 57 / Math.max(120, R);
        view.current.lng = wrapDeg(view.current.lng - dx * k);
        view.current.lat = Math.max(-80, Math.min(80, view.current.lat + dy * k));
        setTip(null);
      }
      holdRotation(3500); kickNow();
    };
    const up = (e: PointerEvent) => {
      if (!pointers.has(e.pointerId)) return;
      pointers.delete(e.pointerId);
      if (pointers.size === 0) {
        dragging = false;
        if (moved < 5) {
          const { x, y } = local(e);
          const hit = hitTest(x, y);
          if (hit?.kind === "arc") selectRef.current(hit.d as ArcDatum);
        }
        canvas.style.cursor = "grab";
      }
      kickNow();
    };
    const leave = () => { if (!dragging) { setTip(null); hoverArc.current = null; } };
    const wheel = (e: WheelEvent) => {
      const u = ui.current;
      if (!(u.coarse ? u.armed : u.zoomHot)) return;
      e.preventDefault();
      view.current.zoom = Math.max(ZOOM_MIN, Math.min(ZOOM_MAX, view.current.zoom * Math.exp(-e.deltaY * 0.0015)));
      anim.current = null; holdRotation(3500); kickNow();
    };
    canvas.addEventListener("pointerdown", down);
    canvas.addEventListener("pointermove", move);
    canvas.addEventListener("pointerup", up);
    canvas.addEventListener("pointercancel", up);
    canvas.addEventListener("pointerleave", leave);
    canvas.addEventListener("wheel", wheel, { passive: false });
    const ro = new ResizeObserver(resize);
    ro.observe(canvas);
    const io = new IntersectionObserver((es) => { visible = es[0]?.isIntersecting ?? true; if (visible) kickNow(); });
    io.observe(canvas);
    resize();
    return () => {
      cancelled = true;
      if (raf) cancelAnimationFrame(raf);
      ro.disconnect(); io.disconnect();
      canvas.removeEventListener("pointerdown", down);
      canvas.removeEventListener("pointermove", move);
      canvas.removeEventListener("pointerup", up);
      canvas.removeEventListener("pointercancel", up);
      canvas.removeEventListener("pointerleave", leave);
      canvas.removeEventListener("wheel", wheel);
    };
    // The loop reads everything live through refs; it is set up once.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (arcs.length === 0) return null;

  const selectedArc = selected ? arcs.find((a) => a.id === selected) ?? null : null;
  const maxTop = topRoutes[0]?.count || 1;
  const legend = coarse ? (armed ? strings.legendTouchArmed : strings.legendTouch) : strings.legend;
  const touchLive = !coarse || armed;

  return (
    <div className="relative min-w-0">
      <p id={hintId} className="sr-only">{strings.stageHint}</p>
      <div
        tabIndex={0}
        role="group"
        aria-label={strings.stageLabel}
        aria-describedby={hintId}
        onKeyDown={onKeyDown}
        onFocus={() => { ui.current.zoomHot = true; }}
        onBlur={() => { ui.current.zoomHot = false; }}
        onPointerEnter={(e) => { if (e.pointerType !== "touch") ui.current.zoomHot = true; }}
        onPointerLeave={() => { ui.current.zoomHot = false; }}
        className="globe-stage relative w-full overflow-hidden rounded-card ring-1 ring-ink-1/10
                   focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-glow"
        style={{ height: stageH }}
      >
        <canvas
          ref={canvasRef}
          aria-hidden
          className="absolute inset-0 h-full w-full"
          style={{ cursor: "grab", touchAction: touchLive ? "none" : "pan-y" }}
        />

        {!landReady && (
          <div className="absolute inset-0 grid place-items-center pointer-events-none">
            <div className="w-44 h-44 rounded-full bg-brand-glow/10 ring-1 ring-brand-glow/20 animate-pulse" />
            <span className="sr-only">{strings.loading}</span>
          </div>
        )}

        {/* Hover tooltip (mouse) — positioned by the render loop's hit test. */}
        <div
          ref={tipRef}
          role="status"
          className={`globe-hud pointer-events-none absolute z-10 max-w-[18rem] rounded-control px-2.5 py-1.5 text-xs globe-ink-1 ${tip ? "" : "hidden"}`}
        >
          {tip}
        </div>

        {/* Route / summary badge */}
        <div className="globe-hud absolute top-3 left-3 max-w-[70%] px-3 py-2 rounded-control">
          {selectedArc ? (
            <>
              <div className="globe-ink-1 font-mono text-xs font-bold tracking-tight">
                {selectedArc.from} → {selectedArc.to}
              </div>
              <div className="globe-ink-accent mt-0.5 text-2xs uppercase tracking-wider">
                {fmt(strings.greatCircle, {
                  flights: flightCount(selectedArc.count),
                  km: selectedArc.km.toLocaleString(locale),
                })}
              </div>
            </>
          ) : visitor.legs.length > 0 && strings.yourRoutes && strings.legsKm ? (
            <>
              <div className="globe-ink-1 text-xs font-bold tracking-tight">{strings.yourRoutes}</div>
              <div className="globe-ink-accent mt-0.5 text-2xs uppercase tracking-wider">
                {fmt(strings.legsKm, { legs: visitor.legs.length.toLocaleString(locale), km: visitor.km.toLocaleString(locale) })}
              </div>
            </>
          ) : (
            <>
              <div className="globe-ink-1 text-xs font-bold tracking-tight">{strings.allTimeFlights}</div>
              <div className="globe-ink-info mt-0.5 text-2xs uppercase tracking-wider">
                {fmt(strings.routesAirports, {
                  routes: arcs.length.toLocaleString(locale),
                  airports: points.filter((p) => p.traffic > 0).length.toLocaleString(locale),
                })}
              </div>
            </>
          )}
        </div>

        {/* Controls */}
        <div className="absolute top-3 right-3 flex gap-1.5">
          <button
            type="button"
            className="globe-btn"
            title={rotateOn ? strings.pauseRotation : strings.resumeRotation}
            aria-label={rotateOn ? strings.pauseRotation : strings.resumeRotation}
            aria-pressed={!rotateOn}
            onClick={() => setRotateOn((v) => !v)}
          >
            {rotateOn
              ? <Pause size={15} strokeWidth={2} aria-hidden />
              : <Play size={15} strokeWidth={2} aria-hidden />}
          </button>
          <button
            type="button"
            className="globe-btn"
            title={strings.resetView}
            aria-label={strings.resetView}
            onClick={resetView}
          >
            <Icon.RotateCcw size={15} strokeWidth={2} aria-hidden />
          </button>
        </div>

        {/* Top routes — click to fly */}
        {routesPanel && topRoutes.length > 0 && (
          <nav
            aria-label={strings.topRoutes}
            className="globe-hud absolute right-3 bottom-3 hidden md:block w-56 rounded-control p-3"
          >
            <div className="globe-ink-2 mb-2 text-2xs uppercase tracking-[0.14em]">{strings.topRoutes}</div>
            <ul className="space-y-1">
              {topRoutes.map((a) => (
                <li key={a.id}>
                  <button
                    type="button"
                    onClick={() => selectRoute(a)}
                    aria-pressed={selected === a.id}
                    className={`globe-route ${selected === a.id ? "is-selected" : ""}`}
                  >
                    <span className="flex w-full justify-between gap-2 text-xs">
                      <span className="globe-ink-1 font-mono">{a.from} → {a.to}</span>
                      <span className="globe-ink-accent num">{a.count.toLocaleString(locale)}</span>
                    </span>
                    <span className="globe-meter mt-1 block h-1 w-full overflow-hidden rounded-pill">
                      <span
                        className="globe-meter-fill block h-full rounded-pill"
                        style={{ width: `${(a.count / maxTop) * 100}%` }}
                      />
                    </span>
                  </button>
                </li>
              ))}
            </ul>
          </nav>
        )}

        {/* Touch arming + legend. The md right inset clears the top-routes panel. */}
        <div className={`absolute left-3 bottom-3 flex flex-col items-start gap-2
                        max-w-[calc(100%-1.5rem)] ${routesPanel ? "md:max-w-[calc(100%-15.5rem)]" : ""}`}>
          {coarse && (
            <button
              type="button"
              className="globe-pill"
              aria-pressed={armed}
              onClick={() => setArmed((v) => !v)}
            >
              {armed
                ? <><Icon.Check size={14} strokeWidth={2} aria-hidden />{strings.done}</>
                : <><Icon.Globe2 size={14} strokeWidth={2} aria-hidden />{strings.tapToExplore}</>}
            </button>
          )}
          <p className="globe-ink-2 text-2xs pointer-events-none">{legend}</p>
        </div>
      </div>

      {/* Top routes on phones: a horizontal chip strip below the globe (the
          desktop overlay is hidden md:block), so route fly-to stays reachable. */}
      {chipStrip && topRoutes.length > 0 && (
        <nav aria-label={strings.topRoutes} className="md:hidden mt-2 -mx-1 flex gap-1.5 overflow-x-auto overscroll-x-contain px-1 pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
          {topRoutes.map((a) => (
            <button
              key={a.id}
              type="button"
              onClick={() => selectRoute(a)}
              aria-pressed={selected === a.id}
              className={`shrink-0 inline-flex items-center gap-1.5 min-h-11 rounded-pill border px-3 text-xs font-mono transition-colors ${selected === a.id ? "border-brand bg-brand/10 text-brand-deep" : "border-border bg-surface text-ink-2 hover:text-ink-1"}`}
            >
              <span>{a.from} → {a.to}</span>
              <span className="num text-2xs text-ink-3">{a.count.toLocaleString(locale)}</span>
            </button>
          ))}
        </nav>
      )}
    </div>
  );
}
