import type { Locale } from "@/lib/i18n";

/**
 * Strings introduced by the Phase 3 settings rebuild (profile, preferences,
 * sharing, backup, billing card, billing success page). Kept local (same
 * pattern as app/app/flights/form-strings.ts) so lib/i18n.ts doesn't churn;
 * fold them in later. Existing labels (`settings.*`, `common.*`) still come
 * from lib/i18n via makeT().
 *
 * Safe to import from both Server and Client Components (no server imports).
 */
const en = {
  subtitle: "Profile, preferences, sharing and backups.",
  profileDesc: "Shown on the PDF export and the dashboard greeting.",
  regimeHint: "{authority} · {reference}",
  regimeMeta: "Sets which flight-time limits and recency rules the dashboard checks.",
  avatarHint: "PNG, JPEG or WebP · up to 2 MB",
  avatarUploaded: "Photo updated",
  avatarFailed: "Photo upload failed",
  avatarAlt: "Profile photo",
  preferences: "Preferences",
  preferencesDesc: "How your hours are credited across the app.",
  saveChanges: "Save changes",
  unsavedChanges: "Unsaved changes",
  noChanges: "Everything is saved",
  discard: "Discard",
  savedToast: "Settings saved",
  savedToastBody: "Your profile and preferences are up to date.",
  saveFailed: "Couldn't save settings",
  errUnexpected: "Something went wrong. Please try again.",
  sharing: "Sharing",
  sharingDesc: "A read-only snapshot of your logbook for an examiner, employer or insurer. Anyone with the link can view it — regenerate to invalidate.",
  shareLinkLabel: "Share link",
  noLink: "No share link yet. Create one to get a URL you can hand out.",
  createLink: "Create share link",
  creating: "Creating…",
  copyLink: "Copy link",
  copied: "Link copied",
  copiedBody: "Paste it wherever you need to share your logbook.",
  copyFailed: "Couldn't copy — select the link and copy it manually.",
  openLink: "Open",
  linkCreated: "Share link created",
  regenerate: "Regenerate",
  regenerateTitle: "Regenerate the share link?",
  regenerateBody: "The current link stops working immediately. Anyone you've shared it with will need the new one.",
  regenerateConfirm: "Regenerate link",
  regenerated: "New share link created",
  revoke: "Revoke",
  revokeTitle: "Revoke the share link?",
  revokeBody: "The link stops working immediately. You can create a new one at any time.",
  revokeConfirm: "Revoke link",
  revoked: "Share link revoked",
  shareFailed: "Couldn't update the share link",
  accountDesc: "Managed by your sign-in.",
  billing: "Billing",
  currentPlan: "Current plan",
  manageBilling: "Manage billing",
  upgrade: "Upgrade",
  billingHint: "Update your card, download invoices or cancel in the Stripe portal.",
  backup: "Backup",
  backupDesc: "Download every flight and the ATPL-style PDF as one ZIP. Drop it into Dropbox, Drive or iCloud for off-site safekeeping.",
  backupContents: "Includes flights.csv, logbook.pdf and a README.",
  backupNow: "Backup now",
  backupRendering: "Rendering PDF…",
  backupZipping: "Compressing…",
  backupDone: "Backup downloaded",
  backupDoneBody: "{file} · {n} flights",
  backupFailed: "Backup failed",
  backupEmpty: "Nothing to back up yet — add or import flights first.",
  flightsCount: "{n} flights",
  lastBackup: "Last backup {time}",
  successTitle: "Welcome to Pro, {name}!",
  successTitleNoName: "Welcome to Pro!",
  successBody: "Payment confirmed. Your account tier updates automatically within a few seconds — refresh the dashboard if you don't see it yet.",
  currentTier: "Current tier",
  goDashboard: "Go to dashboard",
} as const;

export type SettingsStringKey = keyof typeof en;
type Table = Record<SettingsStringKey, string>;

const ko: Table = {
  subtitle: "프로필, 환경설정, 공유, 백업.",
  profileDesc: "PDF 내보내기와 대시보드 인사말에 표시됩니다.",
  regimeHint: "{authority} · {reference}",
  regimeMeta: "대시보드에서 확인하는 비행시간 제한과 최신 유지 규정을 결정합니다.",
  avatarHint: "PNG, JPEG 또는 WebP · 최대 2 MB",
  avatarUploaded: "사진이 업데이트되었습니다",
  avatarFailed: "사진 업로드 실패",
  avatarAlt: "프로필 사진",
  preferences: "환경설정",
  preferencesDesc: "앱 전체에서 비행시간을 인정하는 방식입니다.",
  saveChanges: "변경사항 저장",
  unsavedChanges: "저장되지 않은 변경사항",
  noChanges: "모두 저장됨",
  discard: "버리기",
  savedToast: "설정 저장됨",
  savedToastBody: "프로필과 환경설정이 최신 상태입니다.",
  saveFailed: "설정을 저장할 수 없습니다",
  errUnexpected: "문제가 발생했습니다. 다시 시도해 주세요.",
  sharing: "공유",
  sharingDesc: "검사관, 고용주, 보험사에 보여 줄 읽기 전용 로그북 스냅샷입니다. 링크가 있는 누구나 볼 수 있으며, 재생성하면 기존 링크는 무효화됩니다.",
  shareLinkLabel: "공유 링크",
  noLink: "아직 공유 링크가 없습니다. 링크를 만들어 전달하세요.",
  createLink: "공유 링크 만들기",
  creating: "만드는 중…",
  copyLink: "링크 복사",
  copied: "링크가 복사되었습니다",
  copiedBody: "로그북을 공유할 곳에 붙여넣으세요.",
  copyFailed: "복사할 수 없습니다 — 링크를 선택해 직접 복사하세요.",
  openLink: "열기",
  linkCreated: "공유 링크가 생성되었습니다",
  regenerate: "재생성",
  regenerateTitle: "공유 링크를 재생성할까요?",
  regenerateBody: "현재 링크는 즉시 작동을 멈춥니다. 공유했던 사람에게 새 링크를 다시 보내야 합니다.",
  regenerateConfirm: "링크 재생성",
  regenerated: "새 공유 링크가 생성되었습니다",
  revoke: "해지",
  revokeTitle: "공유 링크를 해지할까요?",
  revokeBody: "링크는 즉시 작동을 멈춥니다. 언제든 새로 만들 수 있습니다.",
  revokeConfirm: "링크 해지",
  revoked: "공유 링크가 해지되었습니다",
  shareFailed: "공유 링크를 변경할 수 없습니다",
  accountDesc: "로그인 계정으로 관리됩니다.",
  billing: "결제",
  currentPlan: "현재 요금제",
  manageBilling: "결제 관리",
  upgrade: "업그레이드",
  billingHint: "Stripe 포털에서 카드 변경, 영수증 다운로드, 해지를 할 수 있습니다.",
  backup: "백업",
  backupDesc: "모든 비행과 ATPL 형식 PDF를 하나의 ZIP으로 다운로드합니다. Dropbox, Drive, iCloud에 넣어 안전하게 보관하세요.",
  backupContents: "flights.csv, logbook.pdf, README가 포함됩니다.",
  backupNow: "지금 백업",
  backupRendering: "PDF 생성 중…",
  backupZipping: "압축 중…",
  backupDone: "백업이 다운로드되었습니다",
  backupDoneBody: "{file} · 비행 {n}회",
  backupFailed: "백업 실패",
  backupEmpty: "아직 백업할 내용이 없습니다 — 먼저 비행을 추가하거나 가져오세요.",
  flightsCount: "비행 {n}회",
  lastBackup: "마지막 백업 {time}",
  successTitle: "{name}님, Pro에 오신 것을 환영합니다!",
  successTitleNoName: "Pro에 오신 것을 환영합니다!",
  successBody: "결제가 확인되었습니다. 계정 등급은 몇 초 안에 자동으로 업데이트됩니다 — 보이지 않으면 대시보드를 새로고침하세요.",
  currentTier: "현재 등급",
  goDashboard: "대시보드로 이동",
};

const zh: Table = {
  subtitle: "个人资料、偏好设置、共享与备份。",
  profileDesc: "显示在 PDF 导出和仪表板问候语中。",
  regimeHint: "{authority} · {reference}",
  regimeMeta: "决定仪表板检查的飞行时间限制和近期经历规则。",
  avatarHint: "PNG、JPEG 或 WebP · 最大 2 MB",
  avatarUploaded: "头像已更新",
  avatarFailed: "头像上传失败",
  avatarAlt: "头像",
  preferences: "偏好设置",
  preferencesDesc: "应用中如何计入您的飞行小时。",
  saveChanges: "保存更改",
  unsavedChanges: "有未保存的更改",
  noChanges: "全部已保存",
  discard: "放弃",
  savedToast: "设置已保存",
  savedToastBody: "您的个人资料和偏好设置已是最新。",
  saveFailed: "无法保存设置",
  errUnexpected: "出了点问题，请重试。",
  sharing: "共享",
  sharingDesc: "供检查员、雇主或保险公司查看的只读飞行日志快照。拥有链接的任何人都可以查看——重新生成即可使旧链接失效。",
  shareLinkLabel: "共享链接",
  noLink: "尚无共享链接。创建一个即可获得可分发的 URL。",
  createLink: "创建共享链接",
  creating: "正在创建…",
  copyLink: "复制链接",
  copied: "链接已复制",
  copiedBody: "粘贴到需要分享飞行日志的地方。",
  copyFailed: "无法复制——请选中链接后手动复制。",
  openLink: "打开",
  linkCreated: "共享链接已创建",
  regenerate: "重新生成",
  regenerateTitle: "重新生成共享链接？",
  regenerateBody: "当前链接会立即失效。已收到链接的人需要新的链接。",
  regenerateConfirm: "重新生成链接",
  regenerated: "已创建新的共享链接",
  revoke: "撤销",
  revokeTitle: "撤销共享链接？",
  revokeBody: "链接会立即失效。您可以随时创建新链接。",
  revokeConfirm: "撤销链接",
  revoked: "共享链接已撤销",
  shareFailed: "无法更新共享链接",
  accountDesc: "由您的登录账户管理。",
  billing: "账单",
  currentPlan: "当前方案",
  manageBilling: "管理账单",
  upgrade: "升级",
  billingHint: "在 Stripe 门户更换银行卡、下载发票或取消订阅。",
  backup: "备份",
  backupDesc: "将所有飞行记录和 ATPL 格式 PDF 打包为一个 ZIP 下载。放入 Dropbox、Drive 或 iCloud 以便异地保存。",
  backupContents: "包含 flights.csv、logbook.pdf 和 README。",
  backupNow: "立即备份",
  backupRendering: "正在生成 PDF…",
  backupZipping: "正在压缩…",
  backupDone: "备份已下载",
  backupDoneBody: "{file} · {n} 次飞行",
  backupFailed: "备份失败",
  backupEmpty: "还没有可备份的内容——请先添加或导入飞行记录。",
  flightsCount: "{n} 次飞行",
  lastBackup: "上次备份 {time}",
  successTitle: "{name}，欢迎加入 Pro！",
  successTitleNoName: "欢迎加入 Pro！",
  successBody: "付款已确认。您的账户级别会在几秒内自动更新——如果尚未显示，请刷新仪表板。",
  currentTier: "当前级别",
  goDashboard: "前往仪表板",
};

const es: Table = {
  subtitle: "Perfil, preferencias, compartir y copias de seguridad.",
  profileDesc: "Se muestra en la exportación PDF y en el saludo del panel.",
  regimeHint: "{authority} · {reference}",
  regimeMeta: "Define qué límites de tiempo de vuelo y reglas de vigencia comprueba el panel.",
  avatarHint: "PNG, JPEG o WebP · hasta 2 MB",
  avatarUploaded: "Foto actualizada",
  avatarFailed: "No se pudo subir la foto",
  avatarAlt: "Foto de perfil",
  preferences: "Preferencias",
  preferencesDesc: "Cómo se acreditan tus horas en toda la aplicación.",
  saveChanges: "Guardar cambios",
  unsavedChanges: "Cambios sin guardar",
  noChanges: "Todo está guardado",
  discard: "Descartar",
  savedToast: "Ajustes guardados",
  savedToastBody: "Tu perfil y tus preferencias están al día.",
  saveFailed: "No se pudieron guardar los ajustes",
  errUnexpected: "Algo salió mal. Inténtalo de nuevo.",
  sharing: "Compartir",
  sharingDesc: "Una instantánea de solo lectura de tu bitácora para un examinador, empleador o aseguradora. Cualquiera con el enlace puede verla — regenéralo para invalidarlo.",
  shareLinkLabel: "Enlace para compartir",
  noLink: "Aún no hay enlace. Crea uno para obtener una URL que puedas entregar.",
  createLink: "Crear enlace para compartir",
  creating: "Creando…",
  copyLink: "Copiar enlace",
  copied: "Enlace copiado",
  copiedBody: "Pégalo donde necesites compartir tu bitácora.",
  copyFailed: "No se pudo copiar — selecciona el enlace y cópialo manualmente.",
  openLink: "Abrir",
  linkCreated: "Enlace creado",
  regenerate: "Regenerar",
  regenerateTitle: "¿Regenerar el enlace para compartir?",
  regenerateBody: "El enlace actual deja de funcionar de inmediato. Quien lo tenga necesitará el nuevo.",
  regenerateConfirm: "Regenerar enlace",
  regenerated: "Nuevo enlace creado",
  revoke: "Revocar",
  revokeTitle: "¿Revocar el enlace para compartir?",
  revokeBody: "El enlace deja de funcionar de inmediato. Puedes crear uno nuevo cuando quieras.",
  revokeConfirm: "Revocar enlace",
  revoked: "Enlace revocado",
  shareFailed: "No se pudo actualizar el enlace",
  accountDesc: "Gestionada por tu inicio de sesión.",
  billing: "Facturación",
  currentPlan: "Plan actual",
  manageBilling: "Gestionar facturación",
  upgrade: "Mejorar plan",
  billingHint: "Cambia tu tarjeta, descarga facturas o cancela en el portal de Stripe.",
  backup: "Copia de seguridad",
  backupDesc: "Descarga todos tus vuelos y el PDF estilo ATPL en un solo ZIP. Guárdalo en Dropbox, Drive o iCloud como respaldo externo.",
  backupContents: "Incluye flights.csv, logbook.pdf y un README.",
  backupNow: "Hacer copia ahora",
  backupRendering: "Generando PDF…",
  backupZipping: "Comprimiendo…",
  backupDone: "Copia descargada",
  backupDoneBody: "{file} · {n} vuelos",
  backupFailed: "La copia falló",
  backupEmpty: "Aún no hay nada que respaldar — agrega o importa vuelos primero.",
  flightsCount: "{n} vuelos",
  lastBackup: "Última copia {time}",
  successTitle: "¡Bienvenido a Pro, {name}!",
  successTitleNoName: "¡Bienvenido a Pro!",
  successBody: "Pago confirmado. El nivel de tu cuenta se actualiza automáticamente en unos segundos — actualiza el panel si aún no lo ves.",
  currentTier: "Nivel actual",
  goDashboard: "Ir al panel",
};

const STRINGS: Record<Locale, Table> = { en, ko, zh, es };

export type SettingsT = (key: SettingsStringKey, vars?: Record<string, string | number>) => string;

/** Bound translator for the settings pages; falls back to English, never to the key. */
export function settingsStrings(locale: Locale): SettingsT {
  const table = STRINGS[locale] ?? STRINGS.en;
  return (key, vars) => {
    let str: string = table[key] ?? STRINGS.en[key];
    if (vars) {
      for (const [k, v] of Object.entries(vars)) str = str.split(`{${k}}`).join(String(v));
    }
    return str;
  };
}
