import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { computeTotals } from "@/lib/derive";
import type { Flight } from "@/lib/types";

/**
 * Public, no-auth read-only logbook snapshot. Anyone with the URL can view.
 * The URL token IS the access secret — rotate it from Settings to invalidate.
 *
 * Shows totals + hour-per-aircraft-type breakdown, but no per-flight detail
 * (PII concern — pilot names, route specifics, remarks). Extend later if
 * we want flight-level visibility behind an explicit owner toggle.
 */
export default async function PublicSharePage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params;
  // Bypass RLS — the share token itself is the access check.
  const admin = createAdminClient();

  const { data: profile } = await admin
    .from("profiles")
    .select("id, full_name, license_number, primary_regime, aug_half_credit")
    .eq("share_token", token)
    .maybeSingle();
  if (!profile) notFound();

  // Paginate to bypass PostgREST's 1000-row cap so the totals match what
  // the owner sees on their dashboard.
  const all: Flight[] = [];
  const PAGE = 1000;
  for (let from = 0; ; from += PAGE) {
    const { data } = await admin
      .from("flights")
      .select("*")
      .eq("user_id", profile.id)
      .order("date", { ascending: false })
      .order("id", { ascending: false })
      .range(from, from + PAGE - 1);
    if (!data || data.length === 0) break;
    all.push(...(data as Flight[]));
    if (data.length < PAGE) break;
  }
  const totals = computeTotals(all, { augHalfCredit: Boolean(profile.aug_half_credit) });

  // Sort aircraft types by hours desc for the breakdown table.
  const byType = Object.entries(totals.by_type)
    .filter(([, v]) => v > 0)
    .sort((a, b) => b[1] - a[1]);

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-200">
      <div className="max-w-4xl mx-auto px-6 py-10">
        <header className="flex items-end justify-between flex-wrap gap-3 mb-8 pb-6 border-b border-slate-300">
          <div>
            <div className="text-[10px] uppercase tracking-[0.18em] text-slate-500 font-bold">Pilot Logbook · Read-only snapshot</div>
            <h1 className="text-3xl font-bold text-slate-900 mt-1">{profile.full_name ?? "Pilot"}</h1>
            <div className="text-sm text-slate-500 mt-1">
              {profile.license_number && <span className="font-mono mr-3">{profile.license_number}</span>}
              {profile.primary_regime} · {all.length.toLocaleString()} flights · {totals.total_time.toFixed(1)} hrs total
            </div>
          </div>
          <div className="text-xs text-slate-500 font-mono">{new Date().toISOString().slice(0, 10)}</div>
        </header>

        <section className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-8">
          <Stat label="Total Time" value={totals.total_time} />
          <Stat label="PIC" value={totals.total_pic} />
          <Stat label="Cross-Country" value={totals.xc_total} />
          <Stat label="Instrument" value={totals.inst_total} />
        </section>

        <section className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-10">
          <Stat label="Single Engine" value={totals.se_total} small />
          <Stat label="Multi-Engine" value={totals.me_total} small />
          <Stat label="IFR Approaches" value={totals.ifr_approaches} small integer />
          <Stat label="Sim" value={totals.sim_inst} small />
        </section>

        <section className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="bg-slate-50 px-5 py-3 border-b border-slate-200">
            <h2 className="text-sm font-bold text-slate-800">Time by Aircraft Type</h2>
          </div>
          <table className="w-full text-sm">
            <tbody>
              {byType.map(([type, hrs]) => (
                <tr key={type} className="border-b border-slate-100 last:border-0">
                  <td className="px-5 py-2 font-mono text-slate-700">{type}</td>
                  <td className="px-5 py-2 text-right tabular-nums font-bold text-slate-900">{hrs.toFixed(1)}</td>
                  <td className="px-5 py-2 text-right text-xs text-slate-400 tabular-nums">
                    {/* total_time can be 0 even when by_type has entries (SIM-only
                        flights log into sim_inst, not day/night). Avoid NaN. */}
                    {totals.total_time > 0 ? ((hrs / totals.total_time) * 100).toFixed(1) : "0.0"}%
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </section>

        <footer className="mt-10 text-center text-xs text-slate-400">
          Generated by <span className="font-bold text-slate-600">Pilot Logbook HQ</span>. This is a read-only snapshot;
          totals reflect the pilot&apos;s currently-logged flights at the time of viewing.
        </footer>
      </div>
    </div>
  );
}

function Stat({ label, value, small = false, integer = false }: {
  label: string; value: number; small?: boolean; integer?: boolean;
}) {
  return (
    <div className={`bg-white rounded-xl border border-slate-200 shadow-sm ${small ? "p-3" : "p-4"}`}>
      <div className="text-[10px] font-bold uppercase tracking-[0.12em] text-slate-500">{label}</div>
      <div className={`font-bold tabular-nums text-slate-900 tracking-tight ${small ? "text-xl mt-0.5" : "text-3xl mt-1"}`}>
        {integer ? value.toLocaleString() : value.toFixed(1)}
        {!integer && <span className={`font-normal text-slate-400 ml-1 ${small ? "text-xs" : "text-sm"}`}>hrs</span>}
      </div>
    </div>
  );
}
